import type { OptionSet } from "../../types";

export const imageFoodStateOptions: OptionSet = {
  id: "image_food_state",
  version: "0.1.0",
  label: { zh: "食物状态", en: "Food state" },
  options: [
    {
      id: "image_food_state:crispy_crunchy",
      version: "0.1.0",
      label: { zh: "酥脆", en: "Crispy / crunchy" },
      plain: { zh: "表面酥脆易碎，有嚼劲的口感视觉", en: "Surface is crispy and breakable, visually crunchy" },
      promptFragment: {
        zh: "表面呈现金黄酥脆的质感，有明显的裂纹和碎片感，视觉上透露出易碎易散的特征",
        en: "golden crispy surface with visible cracks and fragments, conveying a delicate and breakable appearance",
      },
      professionalTerms: ["crispy texture", "crunchy surface", "crackle"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:glossy_shiny",
      version: "0.1.0",
      label: { zh: "光泽闪亮", en: "Glossy / shiny" },
      plain: { zh: "油润光泽，闪闪发光的表面", en: "Oily and glossy, shimmering surface" },
      promptFragment: {
        zh: "表面油润发亮，反射灯光呈现高光和镜面质感，显得新鲜多汁且诱人",
        en: "oily and glossy surface with bright highlights and mirror-like sheen, appearing fresh and appetizing",
      },
      professionalTerms: ["glossy surface", "shiny finish", "wet gloss"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:matte",
      version: "0.1.0",
      label: { zh: "哑光", en: "Matte" },
      plain: { zh: "无光泽，柔和的哑光表面", en: "Dull finish, soft matte surface" },
      promptFragment: {
        zh: "表面无高光无反射，呈现温和柔软的哑光质感，色彩均匀而不刺眼",
        en: "non-reflective matte surface with soft and gentle finish, uniform color without harshness",
      },
      professionalTerms: ["matte finish", "flat surface", "non-glossy"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:melting_soft",
      version: "0.1.0",
      label: { zh: "融化/柔软", en: "Melting / soft" },
      plain: { zh: "快要融化，柔软可塑的质感", en: "Melting or soft texture, almost dripping" },
      promptFragment: {
        zh: "表面呈现融化流动状或柔软下垂感，边缘逐渐淡去或滑动，显得温暖且可口",
        en: "surface appears melting or soft with drooping edges, flowing appearance, warm and delectable",
      },
      professionalTerms: ["melting texture", "soft creamy", "yielding surface"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:steaming_hot",
      version: "0.1.0",
      label: { zh: "蒸汽/热气腾腾", en: "Steaming hot" },
      plain: { zh: "热气冒出，刚烹饪好的热食", en: "Steam rising, freshly cooked hot food" },
      promptFragment: {
        zh: "食物上方弥漫热气蒸汽，白色烟雾缠绕，显得刚出炉刚烹饪完成，温暖诱人",
        en: "rising steam and vapor above the food, white wisps circling, conveying freshly cooked warmth and appeal",
      },
      professionalTerms: ["steaming", "hot steam", "vapor wisps"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:juicy_glistening",
      version: "0.1.0",
      label: { zh: "多汁/晶莹", en: "Juicy / glistening" },
      plain: { zh: "汁液充盈，水分充足的鲜活感", en: "Juicy and moist, glistening with liquid" },
      promptFragment: {
        zh: "表面水润饱满，可见汁液光泽，显得新鲜饱满多汁，令人垂涎欲滴",
        en: "moist and plump surface with visible juice shine, appearing fresh and juicy, mouth-watering",
      },
      professionalTerms: ["juicy texture", "moist surface", "wet appearance"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:caramelized_browned",
      version: "0.1.0",
      label: { zh: "焦糖化/褐色", en: "Caramelized / browned" },
      plain: { zh: "深褐色焦香，经过高温烘烤", en: "Deep brown caramelized, roasted at high heat" },
      promptFragment: {
        zh: "表面呈现金棕至深褐色，有烘烤焦香的深色层，显得经过专业烹饪和精心焙烤",
        en: "golden-brown to deep brown surface with a roasted caramelized crust, professionally cooked appearance",
      },
      professionalTerms: ["caramelized", "browned crust", "charred surface"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:fluffy_airy",
      version: "0.1.0",
      label: { zh: "蓬松/轻盈", en: "Fluffy / airy" },
      plain: { zh: "蓬松轻盈，空气感强的口感", en: "Fluffy and light, airy texture" },
      promptFragment: {
        zh: "质地蓬松轻盈，呈现疏松多孔的结构，仿佛能吹散，显得轻飘飘且诱人",
        en: "light and airy texture with a porous open crumb structure, appearing to float, delightfully fluffy",
      },
      professionalTerms: ["fluffy texture", "airy crumb", "light sponge"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:smooth_creamy",
      version: "0.1.0",
      label: { zh: "光滑/奶油质地", en: "Smooth / creamy" },
      plain: { zh: "顺滑奶油状，丝绸般光滑", en: "Smooth and creamy, silky surface" },
      promptFragment: {
        zh: "表面光滑细腻如丝绸，呈现奶油般的质感和光泽，显得温柔顺滑且高级",
        en: "smooth and silky surface with creamy texture and sheen, appearing velvety and luxurious",
      },
      professionalTerms: ["smooth texture", "creamy finish", "velvety"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:frosted_powdered",
      version: "0.1.0",
      label: { zh: "覆粉/糖霜", en: "Frosted / powdered" },
      plain: { zh: "裹粉或覆盖糖霜，表面有粉质", en: "Coated with powder or frosting, dusty surface" },
      promptFragment: {
        zh: "表面均匀覆盖一层粉状物质，如糖粉、面粉或糖衣霜，显得精致可爱",
        en: "evenly coated with a powdery substance like powdered sugar, flour or frosting, appearing delicate and cute",
      },
      professionalTerms: ["powdered surface", "frosted coating", "dusted"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:condensation_frosted_cold",
      version: "0.1.0",
      label: { zh: "结露/冷饮霜", en: "Condensation / frosted cold" },
      plain: { zh: "凝结水珠或冰霜，冷冻饮品表面", en: "Condensation beads or frost, ice-cold beverage surface" },
      promptFragment: {
        zh: "杯身或液体表面凝结密集的冷凝水珠，或覆盖一层冰霜晶体，显得冰爽透心",
        en: "dense condensation beads on glass or surface, or a layer of frost crystals, conveying refreshing coldness",
      },
      professionalTerms: ["condensation", "frost crystals", "cold sweat"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_state:cross_section_fresh_cut",
      version: "0.1.0",
      label: { zh: "截面/新鲜切面", en: "Cross-section / fresh cut" },
      plain: { zh: "刚切开的截面，露出内部结构", en: "Freshly cut cross-section, interior exposed" },
      promptFragment: {
        zh: "展示食物刚切开的截面，露出内部层次结构、纹理和饱满的内部质感，新鲜生动",
        en: "reveals the freshly cut cross-section with visible layers, texture and rich interior structure, appearing fresh and vibrant",
      },
      professionalTerms: ["cross-section", "cut surface", "fresh interior"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
