import type { OptionSet } from "../../types";

export const imageFoodTablewareOptions: OptionSet = {
  id: "image_food_tableware",
  version: "0.1.0",
  label: { zh: "食器/摆盘", en: "Tableware / plating surface" },
  options: [
    {
      id: "image_food_tableware:white_ceramic",
      version: "0.1.0",
      label: { zh: "白瓷", en: "White ceramic" },
      plain: { zh: "经典白色陶瓷盘，干净简洁", en: "Classic white ceramic plate, clean and simple" },
      promptFragment: {
        zh: "白色陶瓷盘或碗，纯净无瑕，简洁优雅，呈现专业餐厅级别的高级感",
        en: "pure white ceramic plate or bowl, pristine and elegant, conveying a professional fine dining presentation",
      },
      professionalTerms: ["white ceramic", "porcelain plate", "clean plate"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:rustic_wood_board",
      version: "0.1.0",
      label: { zh: "乡村木板", en: "Rustic wood board" },
      plain: { zh: "原木或实木板，自然质朴的质感", en: "Natural wood or cutting board, rustic feel" },
      promptFragment: {
        zh: "自然原木色木板或砧板，纹理清晰可见，边缘自然粗糙，散发温暖素朴的气息",
        en: "natural wood grain board or cutting board with visible texture, rustic edges, conveying warm and earthy aesthetic",
      },
      professionalTerms: ["wood board", "rustic platter", "wooden base"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:dark_slate",
      version: "0.1.0",
      label: { zh: "深灰岩板", en: "Dark slate" },
      plain: { zh: "深灰黑色岩板，粗糙质感", en: "Dark gray slate board, rough texture" },
      promptFragment: {
        zh: "深灰至黑色的岩板或石板，表面粗糙带纹理，显得现代艺术感，衬托食物格调高雅",
        en: "dark gray to black slate board with rough textured surface, modern and artistic, enhancing elegant food presentation",
      },
      professionalTerms: ["slate plate", "dark stone", "slate board"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:white_marble",
      version: "0.1.0",
      label: { zh: "白大理石", en: "White marble" },
      plain: { zh: "白色大理石纹理，奢华优雅", en: "White marble with veining, luxurious and elegant" },
      promptFragment: {
        zh: "白色大理石或大理石纹理的表面，带有灰色或黑色纹脉，显得高端奢华且艺术感十足",
        en: "white marble or marble-patterned surface with gray or black veining, appearing luxurious and artistic",
      },
      professionalTerms: ["marble surface", "marble plate", "marble veining"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:clear_glass",
      version: "0.1.0",
      label: { zh: "透明玻璃", en: "Clear glass" },
      plain: { zh: "清晰透明玻璃杯或盘，现代感强", en: "Clear transparent glass cup or plate, modern look" },
      promptFragment: {
        zh: "透明无色玻璃杯、盘或容器，晶莹清澈，光线穿透，显得现代简洁且通透",
        en: "clear transparent glass cup, plate or vessel, crystal clear with light passing through, modern and clean",
      },
      professionalTerms: ["clear glass", "glass vessel", "transparent glass"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:artisan_ceramic_bowl",
      version: "0.1.0",
      label: { zh: "手工陶碗", en: "Artisan ceramic bowl" },
      plain: { zh: "手工制陶碗，不规则釉料，文艺气息", en: "Handmade ceramic bowl, irregular glaze, artistic" },
      promptFragment: {
        zh: "手工制陶瓷碗，形状略显不规则，釉料纹理自然流动，带有手作感和匠人气息，显得独特艺术",
        en: "handmade ceramic bowl with slightly irregular shape, natural glaze flowing patterns, conveying artisanal and unique aesthetic",
      },
      professionalTerms: ["artisan ceramic", "handmade bowl", "rustic pottery"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:dark_moody_platter",
      version: "0.1.0",
      label: { zh: "深色氛围盘", en: "Dark moody platter" },
      plain: { zh: "深色系盘子，呈现神秘优雅气调", en: "Dark-toned platter, moody and elegant atmosphere" },
      promptFragment: {
        zh: "深色或黑色系的盘子或镶边，可能带有金属光泽或无光泽，散发神秘深邃的优雅气质",
        en: "dark or black-toned plate or rim, possibly with metallic sheen or matte finish, conveying mysterious and sophisticated mood",
      },
      professionalTerms: ["dark platter", "moody plate", "dark finish"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:copper_brass_accent",
      version: "0.1.0",
      label: { zh: "铜/黄铜点缀", en: "Copper / brass accent" },
      plain: { zh: "铜色或黄铜元素装饰，奢华温暖", en: "Copper or brass accents, warm and luxurious" },
      promptFragment: {
        zh: "盘子或餐具带有铜色、黄铜或玫瑰金的细节或镶边，闪闪发光，显得奢华温暖且复古精致",
        en: "plate or tableware featuring copper, brass or rose-gold details or trim, gleaming, conveying warm luxury and vintage elegance",
      },
      professionalTerms: ["copper accent", "brass trim", "metallic copper"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:linen_cloth_napkin",
      version: "0.1.0",
      label: { zh: "亚麻/布质餐巾", en: "Linen / cloth napkin" },
      plain: { zh: "亚麻布或棉布餐巾，自然纹理", en: "Linen or cotton cloth napkin, natural texture" },
      promptFragment: {
        zh: "亚麻或棉布质的餐巾，可见布纹和褶皱，柔软自然，显得高档精致且温暖亲近",
        en: "linen or cotton cloth napkin with visible weave and folds, soft and natural, conveying elegant and warm refinement",
      },
      professionalTerms: ["linen napkin", "cloth napkin", "fabric napkin"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_food_tableware:bamboo_woven_mat",
      version: "0.1.0",
      label: { zh: "竹编垫/格垫", en: "Bamboo woven mat" },
      plain: { zh: "竹编织垫，亚洲风格，天然材料", en: "Bamboo woven placemat, Asian style, natural material" },
      promptFragment: {
        zh: "竹编织或草编的垫子，呈现自然的金黄或土黄色，编织纹理清晰，带有亚洲禅意和自然朴素感",
        en: "bamboo or woven grass placemat in natural golden or beige tones, clear weave pattern, conveying Asian zen aesthetic and natural simplicity",
      },
      professionalTerms: ["bamboo mat", "woven placemat", "rattan weave"],
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
