import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imageHairOptions: OptionSet = {
  "id": "image_hair",
  "version": "0.1.0",
  "label": {
    "zh": "发型",
    "en": "Hair"
  },
  "options": [
    {
      "id": "image_hair:long_straight",
      "version": "0.1.0",
      "label": {
        "zh": "长直发",
        "en": "Long Straight"
      },
      "plain": {
        "zh": "过肩的直发",
        "en": "Straight hair past shoulders"
      },
      "professionalTerms": [
        "long straight hair",
        "sleek hair"
      ],
      "promptFragment": {
        "zh": "长直发，发丝顺滑垂落，光泽感强，造型简洁大方",
        "en": "long straight hair with smooth, flowing strands and a healthy sheen, clean and elegant"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:long_wavy",
      "version": "0.1.0",
      "label": {
        "zh": "长卷发",
        "en": "Long Wavy"
      },
      "plain": {
        "zh": "带波浪的长发",
        "en": "Long hair with waves"
      },
      "professionalTerms": [
        "long wavy hair",
        "flowing waves"
      ],
      "promptFragment": {
        "zh": "长卷发，自然波浪起伏，发丝轻盈飘逸，增添浪漫气息",
        "en": "long wavy hair with natural undulating waves, light and flowing, adding a romantic touch"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:short_bob",
      "version": "0.1.0",
      "label": {
        "zh": "短发波波头",
        "en": "Short Bob"
      },
      "plain": {
        "zh": "齐耳短发",
        "en": "Ear-length short bob cut"
      },
      "professionalTerms": [
        "bob cut",
        "short bob"
      ],
      "promptFragment": {
        "zh": "波波头短发，齐耳长度、线条利落，干练又时尚",
        "en": "short bob cut at ear length with crisp, clean lines, chic and polished"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:pixie_cut",
      "version": "0.1.0",
      "label": {
        "zh": "精灵短发",
        "en": "Pixie Cut"
      },
      "plain": {
        "zh": "超短的精灵头发型",
        "en": "Very short pixie style"
      },
      "professionalTerms": [
        "pixie cut",
        "cropped hair"
      ],
      "promptFragment": {
        "zh": "精灵短发，极短的层次感造型，露出五官轮廓，清爽利落",
        "en": "pixie cut with ultra-short layered texture, revealing facial features, fresh and sharp"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:ponytail",
      "version": "0.1.0",
      "label": {
        "zh": "马尾",
        "en": "Ponytail"
      },
      "plain": {
        "zh": "扎成马尾辫",
        "en": "Hair tied in a ponytail"
      },
      "professionalTerms": [
        "ponytail",
        "tied-back hair"
      ],
      "promptFragment": {
        "zh": "马尾辫，发丝束起露出额头和颈部线条，干净有活力",
        "en": "ponytail with hair pulled back to reveal the forehead and neck line, clean and energetic"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:braids",
      "version": "0.1.0",
      "label": {
        "zh": "辫子",
        "en": "Braids"
      },
      "plain": {
        "zh": "编成辫子",
        "en": "Hair in braids"
      },
      "professionalTerms": [
        "braids",
        "plaited hair"
      ],
      "promptFragment": {
        "zh": "编辫子造型，发丝编织成辫，纹理感强，风格多变",
        "en": "braided hair with woven plaits creating rich texture, versatile in style"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:bun_updo",
      "version": "0.1.0",
      "label": {
        "zh": "盘发",
        "en": "Bun Updo"
      },
      "plain": {
        "zh": "头发盘起",
        "en": "Hair pinned up"
      },
      "professionalTerms": [
        "bun",
        "updo",
        "pinned hair"
      ],
      "promptFragment": {
        "zh": "盘发造型，发丝收拢盘起，露出颈肩线条，优雅端庄",
        "en": "bun or updo with hair swept up and pinned, exposing the neck and shoulder line, elegant and poised"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:messy_tousled",
      "version": "0.1.0",
      "label": {
        "zh": "凌乱蓬松",
        "en": "Messy Tousled"
      },
      "plain": {
        "zh": "随意自然的蓬松感",
        "en": "Casual, tousled look"
      },
      "professionalTerms": [
        "messy hair",
        "tousled",
        "bedhead"
      ],
      "promptFragment": {
        "zh": "凌乱蓬松发型，发丝随意散落，营造不经意的慵懒美感",
        "en": "messy tousled hair with strands falling casually, creating an effortless, undone aesthetic"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_hair:curly_coily",
      "version": "0.1.0",
      "label": {
        "zh": "卷发/自然卷",
        "en": "Curly Coily"
      },
      "plain": {
        "zh": "自然卷曲的头发",
        "en": "Naturally curly or coily hair"
      },
      "professionalTerms": [
        "curly hair",
        "coily texture",
        "natural curls"
      ],
      "promptFragment": {
        "zh": "自然卷发，卷曲蓬松的发丝纹理，体积感强、充满生命力",
        "en": "naturally curly or coily hair with springy, voluminous texture, full of life and movement"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
