import type { OptionSet } from "../../types";

export const imageArchStyleOptions: OptionSet = {
  id: "image_arch_style",
  version: "0.1.0",
  label: { zh: "建筑风格", en: "Architectural style" },
  options: [
    {
      id: "image_arch_style:gothic",
      version: "0.1.0",
      label: { zh: "哥特式", en: "Gothic" },
      plain: { zh: "高耸尖拱、肋拱顶、飞扶壁的中世纪教堂风格", en: "Medieval style with pointed arches, ribbed vaults, and flying buttresses" },
      professionalTerms: ["Gothic architecture", "pointed arch", "ribbed vault", "flying buttress"],
      promptFragment: {
        zh: "哥特式建筑，尖拱窗、肋拱顶，纤细的飞扶壁，垂直线条感强烈，精雕细琢的石雕装饰",
        en: "Gothic architecture with pointed arched windows, ribbed vaults, slender flying buttresses, strong vertical emphasis, and intricate stone carvings",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:modernist",
      version: "0.1.0",
      label: { zh: "现代主义", en: "Modernist" },
      plain: { zh: "功能主义、少装饰、玻璃钢铁混凝土的20世纪现代建筑", en: "Functionalist 20th-century architecture with minimal ornament, glass, steel, and concrete" },
      professionalTerms: ["modernist architecture", "functionalism", "International Style", "Bauhaus"],
      promptFragment: {
        zh: "现代主义建筑，纯净几何体量，平屋顶，大面积玻璃幕墙，无装饰立面，功能导向的形式语言",
        en: "modernist architecture with clean geometric volumes, flat roof, large glazed curtain walls, unornamented facades, and form-follows-function language",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:art_deco",
      version: "0.1.0",
      label: { zh: "装饰艺术", en: "Art Deco" },
      plain: { zh: "1920–30年代几何装饰、金属光泽、阶梯状轮廓", en: "1920s–30s geometric ornamentation, metallic sheen, and stepped silhouettes" },
      professionalTerms: ["Art Deco", "chevron", "sunburst motif", "stepped crown"],
      promptFragment: {
        zh: "装饰艺术风格建筑，阶梯状塔楼轮廓，几何花纹浮雕，金色金属细节，竖向线条与放射状太阳纹交替",
        en: "Art Deco building with stepped tower silhouette, geometric relief ornament, gilded metallic accents, and alternating vertical lines with sunburst motifs",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:brutalism",
      version: "0.1.0",
      label: { zh: "粗野主义", en: "Brutalism" },
      plain: { zh: "裸露混凝土、大块体量、粗糙质感的20世纪中期建筑", en: "Raw exposed concrete, massive forms, and rough texture from mid-20th century" },
      professionalTerms: ["brutalism", "béton brut", "raw concrete", "monolithic form"],
      promptFragment: {
        zh: "粗野主义建筑，裸露清水混凝土肌理，厚重悬挑体量，模板印痕可见，阴影深重，强烈的雕塑感",
        en: "brutalist building with raw béton brut texture, massive cantilevered volumes, visible formwork marks, deep shadows, and strong sculptural presence",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:baroque",
      version: "0.1.0",
      label: { zh: "巴洛克", en: "Baroque" },
      plain: { zh: "富丽堂皇、曲线繁复、大量装饰的17–18世纪欧洲建筑", en: "Ornate 17th–18th century European architecture with curved forms and lavish decoration" },
      professionalTerms: ["Baroque architecture", "undulating facade", "gilded interior", "trompe-l'oeil"],
      promptFragment: {
        zh: "巴洛克建筑，波浪起伏的立面轮廓，盘绕柱式，涡旋状檐口，镀金浮雕与壁画交织，富丽堂皇",
        en: "Baroque architecture with undulating facade, twisted Solomonic columns, scrolled cornices, gilded reliefs and frescoes intertwined — lavishly ornate",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:japanese_traditional",
      version: "0.1.0",
      label: { zh: "日式传统", en: "Japanese Traditional" },
      plain: { zh: "飞檐翘角、木结构、枯山水庭院的日本传统建筑", en: "Traditional Japanese architecture with upswept eaves, timber structure, and dry garden" },
      professionalTerms: ["Japanese traditional architecture", "irimoya roof", "shoji", "engawa"],
      promptFragment: {
        zh: "日式传统建筑，大坡度飞檐翘角，榫卯木结构，障子格窗透光，青苔石阶，精致的枯山水庭院",
        en: "traditional Japanese architecture with steeply pitched upswept eaves, mortise-and-tenon timber frame, translucent shoji screens, mossy stone steps, and a refined karesansui dry garden",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:minimalist",
      version: "0.1.0",
      label: { zh: "极简主义", en: "Minimalist" },
      plain: { zh: "单纯几何、白色或单色、极少细节的当代极简建筑", en: "Pure geometry, white or monochrome, near-zero detail in contemporary minimalist architecture" },
      professionalTerms: ["minimalist architecture", "pure geometry", "white box", "void and mass"],
      promptFragment: {
        zh: "极简主义建筑，纯白盒体或单一混凝土面，消隐的接缝与边角，负空间主导，静默而精准的形体",
        en: "minimalist architecture with pure white cube or monolithic concrete surface, seamless concealed joints, dominant negative space, silent and precise form",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:industrial",
      version: "0.1.0",
      label: { zh: "工业风", en: "Industrial" },
      plain: { zh: "裸露管道、钢铁桁架、砖墙的工厂改造或工业美学建筑", en: "Exposed pipes, steel trusses, and brick walls of converted factories or industrial aesthetic" },
      professionalTerms: ["industrial architecture", "exposed structure", "high-tech style", "loft aesthetic"],
      promptFragment: {
        zh: "工业风建筑，裸露钢铁桁架与管道系统，清水砖墙，大跨度钢架结构，金属栏杆，粗犷而坦诚的结构美学",
        en: "industrial-style building with exposed steel trusses and ductwork, bare brick walls, long-span steel frame, metal railings, and a raw honest structural aesthetic",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:neoclassical",
      version: "0.1.0",
      label: { zh: "新古典主义", en: "Neoclassical" },
      plain: { zh: "柱廊、三角山花、对称立面的18–19世纪复兴古典风格", en: "18th–19th century revival with colonnades, pediments, and symmetrical facades" },
      professionalTerms: ["neoclassical architecture", "Doric/Ionic/Corinthian order", "pediment", "portico"],
      promptFragment: {
        zh: "新古典主义建筑，高耸科林斯柱廊，三角形山花，对称立面，白色大理石或石灰岩，庄重典雅",
        en: "neoclassical building with towering Corinthian colonnade, triangular pediment, symmetrical facade, white marble or limestone — stately and dignified",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:contemporary",
      version: "0.1.0",
      label: { zh: "当代风格", en: "Contemporary" },
      plain: { zh: "2000年代以来的当代多元建筑，形态自由、材料混搭", en: "Post-2000 contemporary architecture with free forms and eclectic materials" },
      professionalTerms: ["contemporary architecture", "parametric design", "free-form", "sustainable design"],
      promptFragment: {
        zh: "当代建筑，自由流动的参数化曲面，绿色屋顶与垂直绿化，高性能双层玻璃幕墙，新旧材料并置",
        en: "contemporary building with freely flowing parametric curved surfaces, green roofs and vertical gardens, high-performance double-skin glass facade, old and new materials juxtaposed",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:islamic",
      version: "0.1.0",
      label: { zh: "伊斯兰", en: "Islamic" },
      plain: { zh: "穹顶、尖拱、几何花纹砖雕的伊斯兰建筑传统", en: "Islamic architectural tradition with domes, pointed arches, and geometric brick or tile patterns" },
      professionalTerms: ["Islamic architecture", "muqarnas", "arabesque", "iwan"],
      promptFragment: {
        zh: "伊斯兰建筑，洋葱形穹顶，尖拱廊，蓝色与绿色几何花砖马赛克，精细阿拉伯花纹雕刻，光影迷离",
        en: "Islamic architecture with onion dome, pointed arched colonnades, blue-and-green geometric tile mosaic, fine arabesque carving, and mesmerizing play of light and shadow",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_style:chinese_traditional",
      version: "0.1.0",
      label: { zh: "中国传统", en: "Chinese Traditional" },
      plain: { zh: "飞檐斗拱、红柱黄瓦、中轴对称的中国传统建筑", en: "Traditional Chinese architecture with upswept bracket-set eaves, red columns, yellow-glazed tiles, and axial symmetry" },
      professionalTerms: ["Chinese traditional architecture", "dougong bracket set", "hip-and-gable roof", "red lacquer column"],
      promptFragment: {
        zh: "中国传统建筑，斗拱飞檐，朱红木柱，黄色琉璃瓦，中轴对称布局，白色汉白玉台基，雍容大气",
        en: "traditional Chinese architecture with dougong bracket-set and upswept eaves, vermilion lacquered columns, yellow glazed roof tiles, axially symmetric layout, white marble terrace — majestic and stately",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
