import type { OptionSet } from "../../types";

export const imageArchTypeOptions: OptionSet = {
  id: "image_arch_type",
  version: "0.1.0",
  label: { zh: "建筑类型", en: "Building type" },
  options: [
    {
      id: "image_arch_type:cathedral",
      version: "0.1.0",
      label: { zh: "大教堂", en: "Cathedral" },
      plain: { zh: "高耸的欧式大教堂", en: "Towering European cathedral" },
      professionalTerms: ["cathedral", "nave", "transept", "bell tower"],
      promptFragment: {
        zh: "宏伟大教堂，高耸双塔，玫瑰窗彩色玻璃透光，中殿纵深感极强，石材外立面精雕细刻",
        en: "grand cathedral with soaring twin towers, rose window in stained glass, deep nave perspective, and intricately carved stone facade",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:skyscraper",
      version: "0.1.0",
      label: { zh: "摩天大楼", en: "Skyscraper" },
      plain: { zh: "超高层写字楼或综合体", en: "Supertall office tower or mixed-use high-rise" },
      professionalTerms: ["skyscraper", "curtain wall", "structural core", "penthouse"],
      promptFragment: {
        zh: "摩天大楼，玻璃幕墙反射云彩，尖锐的塔冠刺入天际，俯瞰城市的高空视角，现代都市天际线标志",
        en: "skyscraper with glass curtain wall reflecting clouds, sharp spire piercing the sky, high vantage point overlooking the city, defining the modern urban skyline",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:museum",
      version: "0.1.0",
      label: { zh: "博物馆", en: "Museum" },
      plain: { zh: "博物馆或美术馆建筑", en: "Museum or art gallery building" },
      professionalTerms: ["museum", "gallery", "atrium", "exhibition hall"],
      promptFragment: {
        zh: "博物馆建筑，宽阔的中庭天窗，展览大厅高挑空间，外立面兼具艺术性与庄重感，广场前设雕塑",
        en: "museum building with a wide skylighted atrium, tall exhibition hall volume, artistically monumental facade, and sculpture in the forecourt plaza",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:temple_shrine",
      version: "0.1.0",
      label: { zh: "寺庙/神社", en: "Temple / Shrine" },
      plain: { zh: "东亚宗教寺庙或日本神社", en: "East Asian religious temple or Japanese Shinto shrine" },
      professionalTerms: ["Buddhist temple", "Shinto shrine", "torii gate", "pagoda"],
      promptFragment: {
        zh: "寺庙或神社，朱红鸟居或山门，参道两侧石灯笼，古木遮荫，苔痕斑驳的石阶，宁静圣洁",
        en: "temple or shrine with vermilion torii gate or sanmon gateway, stone lanterns lining the approach path, ancient trees overhead, moss-stained stone steps — serene and sacred",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:residence",
      version: "0.1.0",
      label: { zh: "民居", en: "Residential building" },
      plain: { zh: "民居、别墅或传统村落建筑", en: "Residential house, villa, or traditional vernacular dwelling" },
      professionalTerms: ["vernacular architecture", "dwelling", "courtyard house", "village house"],
      promptFragment: {
        zh: "传统民居或别墅，精致的庭院入口，错落有致的屋面，温馨生活感，与自然环境融合的选址",
        en: "traditional residence or villa with an elegant courtyard entrance, varied rooflines in rhythm, warm domestic atmosphere, sited in harmony with the natural environment",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:bridge",
      version: "0.1.0",
      label: { zh: "桥梁", en: "Bridge" },
      plain: { zh: "跨越水面或峡谷的工程桥梁", en: "Engineering bridge spanning water or a gorge" },
      professionalTerms: ["suspension bridge", "arch bridge", "cable-stayed bridge", "viaduct"],
      promptFragment: {
        zh: "宏伟桥梁，钢缆或拱肋的几何张力，水面倒影，薄雾中若隐若现，远处城市天际线",
        en: "majestic bridge with the geometric tension of cables or arch ribs, mirror reflection on the water, partially veiled in mist, city skyline in the distance",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:library",
      version: "0.1.0",
      label: { zh: "图书馆", en: "Library" },
      plain: { zh: "图书馆或文化建筑", en: "Library or cultural center" },
      professionalTerms: ["library", "reading room", "stacks", "atrium"],
      promptFragment: {
        zh: "图书馆，环形书架直通穹顶，天窗漫射自然光，阅读大厅宁静庄重，知识与建筑的双重震撼",
        en: "library with circular bookshelves rising to a domed ceiling, diffused natural light from skylights, serene and dignified reading hall — a double awe of knowledge and architecture",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:castle",
      version: "0.1.0",
      label: { zh: "城堡", en: "Castle" },
      plain: { zh: "中世纪城堡或防御堡垒", en: "Medieval castle or defensive fortress" },
      professionalTerms: ["castle", "battlements", "keep", "drawbridge", "turret"],
      promptFragment: {
        zh: "中世纪城堡，雉堞城墙，圆形角楼，悬吊吊桥，干涸护城河，古朴石砌肌理，历经沧桑之感",
        en: "medieval castle with crenellated walls, circular corner turrets, raised drawbridge, dry moat, weathered stone texture — carrying the weight of centuries",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:palace",
      version: "0.1.0",
      label: { zh: "宫殿", en: "Palace" },
      plain: { zh: "皇家宫殿或国家重要建筑群", en: "Royal palace or grand state building complex" },
      professionalTerms: ["palace", "grand hall", "colonnade", "formal garden"],
      promptFragment: {
        zh: "宏伟宫殿建筑群，中轴对称，柱廊层叠，前庭广场宽阔，皇家御花园几何修剪整齐，震撼恢宏",
        en: "grand palace complex with axial symmetry, layered colonnades, vast ceremonial forecourt, and geometrically trimmed royal garden — awe-inspiring in scale",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:transit_hub",
      version: "0.1.0",
      label: { zh: "交通枢纽", en: "Transit hub" },
      plain: { zh: "火车站、机场或交通换乘枢纽", en: "Train station, airport, or multi-modal transit hub" },
      professionalTerms: ["train station", "airport terminal", "concourse", "vaulted hall"],
      promptFragment: {
        zh: "交通枢纽大厅，大跨度钢铁拱顶，天窗阳光斜射，旅人川流不息，宏大的公共空间尺度",
        en: "transit hub concourse with a long-span steel arched roof, diagonal sunbeams through skylights, travelers streaming through — grand public space at a monumental scale",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:courtyard_garden",
      version: "0.1.0",
      label: { zh: "庭院/园林", en: "Courtyard / Garden" },
      plain: { zh: "中式园林庭院或欧式对称花园", en: "Chinese garden courtyard or formal European garden" },
      professionalTerms: ["courtyard", "formal garden", "cloister", "peristyle"],
      promptFragment: {
        zh: "典雅庭院或古典园林，曲折游廊，叠石假山，荷花水池，或对称花坛绿篱，静谧美丽",
        en: "elegant courtyard or classical garden with winding colonnaded walkway, layered rockery, lotus pond — or symmetrical parterres and hedgerows — quiet and beautiful",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_type:commercial_complex",
      version: "0.1.0",
      label: { zh: "商业综合体", en: "Commercial complex" },
      plain: { zh: "现代购物中心、商业街区或城市综合体", en: "Modern shopping mall, commercial block, or urban mixed-use complex" },
      professionalTerms: ["shopping mall", "commercial district", "atrium retail", "urban complex"],
      promptFragment: {
        zh: "现代商业综合体，贯通多层的中庭天窗，玻璃电梯通透，品牌旗舰店林立，活力十足的城市商业氛围",
        en: "modern commercial complex with a multi-story glazed atrium, transparent glass elevators, flagship retail stores lining the edges — vibrant urban commercial atmosphere",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
