import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imagePoseOptions: OptionSet = {
  "id": "image_pose",
  "version": "0.1.0",
  "label": {
    "zh": "姿态",
    "en": "Pose"
  },
  "options": [
    {
      "id": "image_pose:standing",
      "version": "0.1.0",
      "label": {
        "zh": "站立",
        "en": "Standing"
      },
      "plain": {
        "zh": "自然站姿",
        "en": "Natural standing pose"
      },
      "professionalTerms": [
        "standing pose",
        "upright posture"
      ],
      "promptFragment": {
        "zh": "自然站立姿态，身体放松、重心平稳，适合展示整体造型",
        "en": "natural standing pose with a relaxed body and balanced weight, ideal for showcasing the overall look"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:sitting",
      "version": "0.1.0",
      "label": {
        "zh": "坐姿",
        "en": "Sitting"
      },
      "plain": {
        "zh": "坐在椅子或地面上",
        "en": "Seated on chair or ground"
      },
      "professionalTerms": [
        "sitting pose",
        "seated posture"
      ],
      "promptFragment": {
        "zh": "坐姿，坐在椅子或地面上，身体放松自然，营造亲切随和的感觉",
        "en": "sitting pose on a chair or ground, relaxed and natural body language, conveying an approachable casual vibe"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:walking",
      "version": "0.1.0",
      "label": {
        "zh": "行走",
        "en": "Walking"
      },
      "plain": {
        "zh": "走路中的动态姿态",
        "en": "Dynamic walking motion"
      },
      "professionalTerms": [
        "walking pose",
        "mid-stride"
      ],
      "promptFragment": {
        "zh": "行走中的动态姿态，步伐自然、衣摆微动，画面充满活力",
        "en": "dynamic walking pose with a natural stride and gently moving fabric, adding life and energy to the scene"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:side_profile",
      "version": "0.1.0",
      "label": {
        "zh": "侧身",
        "en": "Side Profile"
      },
      "plain": {
        "zh": "身体侧对镜头",
        "en": "Body turned to the side"
      },
      "professionalTerms": [
        "side profile",
        "three-quarter view",
        "turned pose"
      ],
      "promptFragment": {
        "zh": "侧身姿态，身体转向一侧，展现轮廓线条和侧面轮廓",
        "en": "side profile pose with the body turned to reveal silhouette lines and the contour of the face"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:looking_back",
      "version": "0.1.0",
      "label": {
        "zh": "回眸",
        "en": "Looking Back"
      },
      "plain": {
        "zh": "回头看向镜头",
        "en": "Turning head back to look at camera"
      },
      "professionalTerms": [
        "over-the-shoulder glance",
        "looking back"
      ],
      "promptFragment": {
        "zh": "回眸姿态，身体侧转、目光回望镜头，自然而有故事感",
        "en": "looking back over the shoulder, body turned away while the gaze returns to camera, natural and evocative"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:leaning",
      "version": "0.1.0",
      "label": {
        "zh": "倚靠",
        "en": "Leaning"
      },
      "plain": {
        "zh": "靠在墙或物体上",
        "en": "Leaning against a wall or object"
      },
      "professionalTerms": [
        "leaning pose",
        "casual lean"
      ],
      "promptFragment": {
        "zh": "倚靠姿态，身体靠在墙面或物体上，姿态轻松随意",
        "en": "leaning pose against a wall or surface, conveying a relaxed and casual demeanor"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:arms_crossed",
      "version": "0.1.0",
      "label": {
        "zh": "抱臂",
        "en": "Arms Crossed"
      },
      "plain": {
        "zh": "双臂交叉在胸前",
        "en": "Arms crossed over chest"
      },
      "professionalTerms": [
        "arms crossed",
        "confident stance"
      ],
      "promptFragment": {
        "zh": "双臂交叉抱于胸前，姿态自信从容，传递坚定感",
        "en": "arms crossed over the chest in a confident and composed stance, projecting self-assurance"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_pose:reclining",
      "version": "0.1.0",
      "label": {
        "zh": "躺卧",
        "en": "Reclining"
      },
      "plain": {
        "zh": "半躺或躺下的放松姿态",
        "en": "Lying back or reclining pose"
      },
      "professionalTerms": [
        "reclining pose",
        "lounging"
      ],
      "promptFragment": {
        "zh": "半躺或躺卧姿态，身体放松舒展，营造慵懒惬意的氛围",
        "en": "reclining or lying-back pose with a relaxed, extended body, creating a laid-back and comfortable atmosphere"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
