import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imageCameraOptions: OptionSet = {
  "id": "image_camera",
  "version": "0.1.0",
  "label": {
    "zh": "镜头",
    "en": "Camera"
  },
  "options": [
    {
      "id": "image_camera:35mm_wide",
      "version": "0.1.0",
      "label": {
        "zh": "35mm 广角",
        "en": "35mm Wide"
      },
      "plain": {
        "zh": "视野稍广，适合街头和环境人像",
        "en": "Slightly wide field of view, great for street and environmental portraits"
      },
      "professionalTerms": [
        "35mm lens",
        "wide-angle perspective",
        "environmental portrait"
      ],
      "promptFragment": {
        "zh": "35mm 广角镜头，视野开阔自然，适合街头和环境人像，透视略有拉伸感",
        "en": "35mm wide-angle lens with an open natural field of view, suited for street and environmental portraits, subtle perspective extension"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:50mm_standard",
      "version": "0.1.0",
      "label": {
        "zh": "50mm 标准",
        "en": "50mm Standard"
      },
      "plain": {
        "zh": "接近人眼视角，最自然的透视",
        "en": "Closest to human eye perspective, most natural rendering"
      },
      "professionalTerms": [
        "50mm lens",
        "standard lens",
        "natural perspective"
      ],
      "promptFragment": {
        "zh": "50mm 标准镜头，最接近人眼视角，透视自然无畸变",
        "en": "50mm standard lens closest to human eye perspective, natural rendering with no distortion"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:85mm_portrait",
      "version": "0.1.0",
      "label": {
        "zh": "85mm 人像",
        "en": "85mm Portrait"
      },
      "plain": {
        "zh": "经典人像焦段，背景虚化柔和",
        "en": "Classic portrait focal length with smooth background blur"
      },
      "professionalTerms": [
        "85mm lens",
        "portrait lens",
        "telephoto compression"
      ],
      "promptFragment": {
        "zh": "85mm 人像镜头，浅景深柔化背景，主体突出、面部比例自然",
        "en": "85mm portrait lens with shallow depth of field, softly blurred background isolating the subject with natural facial proportions"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:200mm_telephoto",
      "version": "0.1.0",
      "label": {
        "zh": "200mm 长焦",
        "en": "200mm Telephoto"
      },
      "plain": {
        "zh": "强烈压缩感，适合远距离特写",
        "en": "Strong compression effect, ideal for distant close-ups"
      },
      "professionalTerms": [
        "200mm lens",
        "telephoto",
        "compression effect",
        "background separation"
      ],
      "promptFragment": {
        "zh": "200mm 长焦镜头，强烈空间压缩感，远距离也能拍出紧凑特写",
        "en": "200mm telephoto lens with strong spatial compression, tight framing even from a distance"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:macro_lens",
      "version": "0.1.0",
      "label": {
        "zh": "微距镜头",
        "en": "Macro Lens"
      },
      "plain": {
        "zh": "极近距离拍摄，展现微小细节",
        "en": "Extreme close-up, revealing tiny details"
      },
      "professionalTerms": [
        "macro lens",
        "1:1 magnification",
        "extreme close-up"
      ],
      "promptFragment": {
        "zh": "微距镜头，极近距离拍摄，展现肉眼难以察觉的微小细节和纹理",
        "en": "macro lens at extreme close-up distance, revealing tiny details and textures invisible to the naked eye"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:wide_aperture_bokeh",
      "version": "0.1.0",
      "label": {
        "zh": "大光圈虚化",
        "en": "Wide Aperture Bokeh"
      },
      "plain": {
        "zh": "主体清晰、背景模糊",
        "en": "Sharp subject with blurred background"
      },
      "professionalTerms": [
        "shallow depth of field",
        "wide aperture",
        "bokeh background"
      ],
      "promptFragment": {
        "zh": "浅景深效果，主体锐利清晰、背景柔和虚化，视觉焦点集中",
        "en": "shallow depth of field with a tack-sharp subject against a soft, smoothly blurred background, drawing focus to the center"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:deep_dof",
      "version": "0.1.0",
      "label": {
        "zh": "深景深",
        "en": "Deep Depth of Field"
      },
      "plain": {
        "zh": "前景到背景都清晰",
        "en": "Sharp from foreground to background"
      },
      "professionalTerms": [
        "deep depth of field",
        "narrow aperture",
        "everything in focus"
      ],
      "promptFragment": {
        "zh": "深景深效果，从前景到远景全部清晰锐利，画面信息丰富",
        "en": "deep depth of field keeping foreground through background in sharp focus, rich in visual detail throughout"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:dslr_quality",
      "version": "0.1.0",
      "label": {
        "zh": "单反画质",
        "en": "DSLR Quality"
      },
      "plain": {
        "zh": "专业相机质感，高细节低噪点",
        "en": "Professional camera look, high detail and low noise"
      },
      "professionalTerms": [
        "DSLR",
        "full-frame sensor",
        "professional camera"
      ],
      "promptFragment": {
        "zh": "专业单反相机画质，高分辨率传感器，细节丰富、噪点极低",
        "en": "professional DSLR camera quality from a high-resolution sensor, rich detail with minimal noise"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:smartphone_photo",
      "version": "0.1.0",
      "label": {
        "zh": "手机拍照",
        "en": "Smartphone Photo"
      },
      "plain": {
        "zh": "手机随手拍的真实感",
        "en": "Casual smartphone snapshot feel"
      },
      "professionalTerms": [
        "smartphone photography",
        "mobile photo",
        "casual snapshot"
      ],
      "promptFragment": {
        "zh": "智能手机拍摄质感，自然随拍的真实感，略带广角透视",
        "en": "smartphone photography aesthetic with a casual, authentic snapshot feel and slight wide-angle perspective"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_camera:film_grain",
      "version": "0.1.0",
      "label": {
        "zh": "胶片质感",
        "en": "Film Grain"
      },
      "plain": {
        "zh": "胶片相机的颗粒感和色调",
        "en": "Film grain texture and color tone"
      },
      "professionalTerms": [
        "film photography",
        "analog grain",
        "35mm film"
      ],
      "promptFragment": {
        "zh": "胶片相机质感，自然的银盐颗粒和微妙的色彩偏移，复古而有温度",
        "en": "film camera aesthetic with organic silver-halide grain and subtle color shifts, vintage and warm"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
