import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imageOutfitOptions: OptionSet = {
  "id": "image_outfit",
  "version": "0.1.0",
  "label": {
    "zh": "着装",
    "en": "Outfit"
  },
  "options": [
    {
      "id": "image_outfit:casual_wear",
      "version": "0.1.0",
      "label": {
        "zh": "休闲装",
        "en": "Casual Wear"
      },
      "plain": {
        "zh": "日常休闲穿搭",
        "en": "Everyday casual clothing"
      },
      "professionalTerms": [
        "casual wear",
        "everyday outfit"
      ],
      "promptFragment": {
        "zh": "日常休闲穿搭，舒适随性，适合轻松生活场景",
        "en": "everyday casual wear with a comfortable and laid-back feel, suited for relaxed lifestyle scenes"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:formal_suit",
      "version": "0.1.0",
      "label": {
        "zh": "正装",
        "en": "Formal Suit"
      },
      "plain": {
        "zh": "西装或其他正式服装",
        "en": "Suit or other formal attire"
      },
      "professionalTerms": [
        "formal attire",
        "suit",
        "business wear"
      ],
      "promptFragment": {
        "zh": "正式西装或礼服，剪裁合体、面料考究，展现专业和精致感",
        "en": "formal suit or gown with tailored fit and refined fabric, conveying professionalism and sophistication"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:streetwear",
      "version": "0.1.0",
      "label": {
        "zh": "街头潮流",
        "en": "Streetwear"
      },
      "plain": {
        "zh": "街头风格，宽松舒适",
        "en": "Urban street style, relaxed and trendy"
      },
      "professionalTerms": [
        "streetwear",
        "urban fashion"
      ],
      "promptFragment": {
        "zh": "街头潮流风格，宽松版型、层次叠穿，个性鲜明",
        "en": "streetwear style with oversized silhouettes and layered combinations, bold and expressive"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:elegant_dress",
      "version": "0.1.0",
      "label": {
        "zh": "优雅裙装",
        "en": "Elegant Dress"
      },
      "plain": {
        "zh": "优雅的连衣裙或礼服",
        "en": "Elegant dress or gown"
      },
      "professionalTerms": [
        "elegant dress",
        "gown",
        "evening wear"
      ],
      "promptFragment": {
        "zh": "优雅连衣裙或礼服，面料垂坠飘逸，展现女性柔美气质",
        "en": "elegant dress or gown with flowing drapery, highlighting feminine grace and poise"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:sporty_athletic",
      "version": "0.1.0",
      "label": {
        "zh": "运动装",
        "en": "Athletic Wear"
      },
      "plain": {
        "zh": "运动或健身服装",
        "en": "Sports or fitness clothing"
      },
      "professionalTerms": [
        "athletic wear",
        "activewear",
        "sportswear"
      ],
      "promptFragment": {
        "zh": "运动健身服装，贴合身形、功能面料，充满活力感",
        "en": "athletic wear with body-hugging fit and performance fabric, conveying energy and vitality"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:minimalist_simple",
      "version": "0.1.0",
      "label": {
        "zh": "简约风",
        "en": "Minimalist"
      },
      "plain": {
        "zh": "简洁干净的基础款",
        "en": "Clean and simple basics"
      },
      "professionalTerms": [
        "minimalist fashion",
        "clean lines",
        "basics"
      ],
      "promptFragment": {
        "zh": "简约基础款穿搭，线条干净、色彩克制，高级感十足",
        "en": "minimalist basics with clean lines and restrained colors, understated yet refined"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_outfit:traditional_ethnic",
      "version": "0.1.0",
      "label": {
        "zh": "传统民族服饰",
        "en": "Traditional Ethnic Wear"
      },
      "plain": {
        "zh": "各国传统服装",
        "en": "Traditional cultural clothing"
      },
      "professionalTerms": [
        "traditional wear",
        "ethnic attire",
        "cultural costume"
      ],
      "promptFragment": {
        "zh": "传统民族服饰，工艺细节丰富、色彩鲜明，展现文化底蕴",
        "en": "traditional ethnic attire with rich craftsmanship details and vibrant colors, showcasing cultural heritage"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
