import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imageProductMaterialOptions: OptionSet = {
  "id": "image_product_material",
  "version": "0.1.0",
  "label": {
    "zh": "产品材质",
    "en": "Product Material"
  },
  "options": [
    {
      "id": "image_product_material:metal",
      "version": "0.1.0",
      "label": {
        "zh": "金属",
        "en": "Metal"
      },
      "plain": {
        "zh": "金属质感，有光泽",
        "en": "Metallic finish with sheen"
      },
      "professionalTerms": [
        "metal",
        "metallic surface",
        "brushed metal"
      ],
      "promptFragment": {
        "zh": "金属材质，表面光泽或哑光处理，反射光线、质感硬朗",
        "en": "metal material with polished or matte finish, light-reflective with a sturdy, industrial feel"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:glass",
      "version": "0.1.0",
      "label": {
        "zh": "玻璃",
        "en": "Glass"
      },
      "plain": {
        "zh": "透明或磨砂玻璃",
        "en": "Clear or frosted glass"
      },
      "professionalTerms": [
        "glass",
        "translucent",
        "frosted glass"
      ],
      "promptFragment": {
        "zh": "玻璃材质，透明或半透明，光线穿透折射，通透精致",
        "en": "glass material, transparent or translucent, with light passing through and refracting, refined and crystalline"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:leather",
      "version": "0.1.0",
      "label": {
        "zh": "皮革",
        "en": "Leather"
      },
      "plain": {
        "zh": "皮革质感，柔软或硬挺",
        "en": "Leather texture, soft or firm"
      },
      "professionalTerms": [
        "leather",
        "genuine leather",
        "leather grain"
      ],
      "promptFragment": {
        "zh": "皮革材质，天然纹理细腻、触感温润，散发高级质感",
        "en": "leather material with fine natural grain and a warm, supple touch, exuding premium quality"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:wood",
      "version": "0.1.0",
      "label": {
        "zh": "木质",
        "en": "Wood"
      },
      "plain": {
        "zh": "天然木纹纹理",
        "en": "Natural wood grain texture"
      },
      "professionalTerms": [
        "wood",
        "wooden",
        "wood grain",
        "timber"
      ],
      "promptFragment": {
        "zh": "木质材质，天然木纹清晰可见，温暖质朴、手感自然",
        "en": "wood material with visible natural grain patterns, warm and organic to the touch"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:fabric_textile",
      "version": "0.1.0",
      "label": {
        "zh": "织物",
        "en": "Fabric Textile"
      },
      "plain": {
        "zh": "布料或纺织品",
        "en": "Cloth or woven textile"
      },
      "professionalTerms": [
        "fabric",
        "textile",
        "woven material"
      ],
      "promptFragment": {
        "zh": "织物材质，布面纹理可见，柔软有垂感，触感亲切",
        "en": "fabric textile material with visible woven texture, soft drape and a comfortable, approachable feel"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:ceramic",
      "version": "0.1.0",
      "label": {
        "zh": "陶瓷",
        "en": "Ceramic"
      },
      "plain": {
        "zh": "陶瓷质感，光滑细腻",
        "en": "Ceramic texture, smooth and refined"
      },
      "professionalTerms": [
        "ceramic",
        "porcelain",
        "glazed"
      ],
      "promptFragment": {
        "zh": "陶瓷材质，釉面光滑细腻，质感温润、色泽内敛",
        "en": "ceramic material with a smooth glazed surface, warm to the touch with subtle, restrained coloring"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:plastic_resin",
      "version": "0.1.0",
      "label": {
        "zh": "塑料/树脂",
        "en": "Plastic Resin"
      },
      "plain": {
        "zh": "塑料或树脂质感",
        "en": "Plastic or resin finish"
      },
      "professionalTerms": [
        "plastic",
        "resin",
        "polymer"
      ],
      "promptFragment": {
        "zh": "塑料或树脂材质，表面均匀光滑，色彩饱和、造型自由",
        "en": "plastic or resin material with a uniform smooth surface, saturated color and free-form molding"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:stone_marble",
      "version": "0.1.0",
      "label": {
        "zh": "石材/大理石",
        "en": "Stone Marble"
      },
      "plain": {
        "zh": "天然石材纹理",
        "en": "Natural stone or marble veining"
      },
      "professionalTerms": [
        "stone",
        "marble",
        "granite",
        "natural stone"
      ],
      "promptFragment": {
        "zh": "石材或大理石材质，天然纹理独特、质感厚重沉稳",
        "en": "stone or marble material with unique natural veining, substantial weight and a grounded, solid feel"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_product_material:carbon_fiber",
      "version": "0.1.0",
      "label": {
        "zh": "碳纤维",
        "en": "Carbon fiber"
      },
      "plain": {
        "zh": "碳纤维编织纹理，轻量高强、哑光黑",
        "en": "Woven carbon-fiber texture, lightweight and strong, matte black"
      },
      "professionalTerms": [
        "carbon fiber",
        "carbon fibre",
        "woven carbon",
        "twill weave",
        "matte black composite"
      ],
      "promptFragment": {
        "zh": "碳纤维材质，黑色编织纹理，轻量高强的高科技质感",
        "en": "carbon fiber material with woven black texture, a lightweight high-tech finish"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
