import type { OptionSet } from "../../types";

/** AUTO-GENERATED by .research/scripts/gen-option-sets.mjs from
 *  proposed-dimensions.json (Slice 2 / Phase B). Prototype-only dimension —
 *  registered globally but referenced only by image-prompt-agent.worktype.
 *  Regenerate: node .research/scripts/gen-option-sets.mjs */
export const imageWeatherOptions: OptionSet = {
  "id": "image_weather",
  "version": "0.1.0",
  "label": {
    "zh": "天气",
    "en": "Weather"
  },
  "options": [
    {
      "id": "image_weather:sunny_clear",
      "version": "0.1.0",
      "label": {
        "zh": "晴天",
        "en": "Sunny Clear"
      },
      "plain": {
        "zh": "晴朗无云",
        "en": "Clear blue sky, bright sunshine"
      },
      "professionalTerms": [
        "clear sky",
        "sunny",
        "bright daylight"
      ],
      "promptFragment": {
        "zh": "晴朗天气，万里无云、阳光明媚，光线充足、色彩鲜艳",
        "en": "sunny clear weather with a cloudless sky and bright sunshine, ample light and vivid colors"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:overcast_cloudy",
      "version": "0.1.0",
      "label": {
        "zh": "多云",
        "en": "Overcast Cloudy"
      },
      "plain": {
        "zh": "云层覆盖，光线柔和",
        "en": "Cloudy sky, soft diffused light"
      },
      "professionalTerms": [
        "overcast",
        "cloudy",
        "overcast sky"
      ],
      "promptFragment": {
        "zh": "多云天气，云层覆盖天空，光线柔和均匀、阴影淡雅",
        "en": "overcast cloudy sky with soft, even diffused lighting and gentle, understated shadows"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:rain",
      "version": "0.1.0",
      "label": {
        "zh": "雨天",
        "en": "Rainy"
      },
      "plain": {
        "zh": "下雨，湿润反光",
        "en": "Rain, wet surfaces and reflections"
      },
      "professionalTerms": [
        "rain",
        "rainy",
        "wet surfaces",
        "raindrops"
      ],
      "promptFragment": {
        "zh": "雨天，雨滴飘落、地面湿润反光，空气清新、氛围感强",
        "en": "rainy weather with falling raindrops and wet reflective surfaces, fresh atmosphere with strong mood"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:snow",
      "version": "0.1.0",
      "label": {
        "zh": "雪天",
        "en": "Snowy"
      },
      "plain": {
        "zh": "下雪，白色覆盖",
        "en": "Snowfall, white landscape"
      },
      "professionalTerms": [
        "snow",
        "snowfall",
        "snowy",
        "winter snow"
      ],
      "promptFragment": {
        "zh": "雪天，白雪覆盖大地，光线清冷柔和、画面纯净宁静",
        "en": "snowy weather with snow blanketing the ground, cool soft light and a pure, tranquil scene"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:fog_mist",
      "version": "0.1.0",
      "label": {
        "zh": "雾",
        "en": "Fog Mist"
      },
      "plain": {
        "zh": "薄雾或浓雾",
        "en": "Light mist or dense fog"
      },
      "professionalTerms": [
        "fog",
        "mist",
        "hazy",
        "foggy"
      ],
      "promptFragment": {
        "zh": "雾天，薄雾弥漫远处轮廓模糊，空气湿润、氛围神秘",
        "en": "foggy or misty weather with distant contours softened by haze, moist air and a mysterious atmosphere"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:storm",
      "version": "0.1.0",
      "label": {
        "zh": "暴风雨",
        "en": "Storm"
      },
      "plain": {
        "zh": "暴风雨，戏剧性天气",
        "en": "Stormy weather, dramatic atmosphere"
      },
      "professionalTerms": [
        "storm",
        "thunderstorm",
        "dramatic weather"
      ],
      "promptFragment": {
        "zh": "暴风雨天气，乌云翻涌、风雨交加，画面充满戏剧张力",
        "en": "stormy weather with dark roiling clouds and driving rain, full of dramatic tension"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    },
    {
      "id": "image_weather:windy",
      "version": "0.1.0",
      "label": {
        "zh": "大风",
        "en": "Windy"
      },
      "plain": {
        "zh": "风吹动头发和衣物",
        "en": "Wind blowing hair and clothing"
      },
      "professionalTerms": [
        "windy",
        "wind-blown",
        "breeze"
      ],
      "promptFragment": {
        "zh": "大风天气，发丝和衣物被风吹起飘动，画面充满动感",
        "en": "windy weather with hair and clothing caught and billowing in the wind, adding dynamic movement"
      },
      "appliesTo": [
        "generic_image"
      ],
      "riskHint": {
        "zh": "",
        "en": ""
      }
    }
  ]
};
