import type { OptionSet } from "../../types";

export const imageArchMaterialOptions: OptionSet = {
  id: "image_arch_material",
  version: "0.1.0",
  label: { zh: "建筑材质", en: "Building material" },
  options: [
    {
      id: "image_arch_material:stone_masonry",
      version: "0.1.0",
      label: { zh: "石材砌筑", en: "Stone masonry" },
      plain: { zh: "自然石材或切割石块砌成的建筑表面", en: "Natural or cut stone blocks forming the building surface" },
      professionalTerms: ["stone masonry", "ashlar", "rustication", "coursed stonework"],
      promptFragment: {
        zh: "石材砌筑立面，块石接缝清晰可见，表面凹凸粗粝或精细打磨，光线下立体感强，历史沉淀感",
        en: "stone masonry facade with clearly visible block joints, rough rusticated or finely dressed surface, strong three-dimensional texture in light, evoking historical depth",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:glass_curtain",
      version: "0.1.0",
      label: { zh: "玻璃幕墙", en: "Glass curtain wall" },
      plain: { zh: "全玻璃或玻璃钢结合的现代幕墙系统", en: "Full glass or glass-and-steel modern curtain wall system" },
      professionalTerms: ["curtain wall", "unitized glazing", "structural glass", "double-skin facade"],
      promptFragment: {
        zh: "玻璃幕墙立面，高反射率镀膜玻璃映照天空与周边，分格线条精细，光线随时间变换色彩",
        en: "glass curtain wall facade with high-reflectance coated glass mirroring sky and surroundings, fine mullion grid, colors shifting with the changing light throughout the day",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:concrete",
      version: "0.1.0",
      label: { zh: "清水混凝土", en: "Exposed concrete" },
      plain: { zh: "裸露或打磨的混凝土建筑表面", en: "Raw or polished exposed concrete building surface" },
      professionalTerms: ["béton brut", "architectural concrete", "board-formed concrete", "polished concrete"],
      promptFragment: {
        zh: "清水混凝土表面，模板纹理清晰，灰色调克制静默，细腻与粗粝并存，光影雕塑感强烈",
        en: "exposed concrete surface with visible formwork texture, restrained gray tone, fine and rough qualities coexisting, powerful sculptural light-and-shadow effect",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:wood_timber",
      version: "0.1.0",
      label: { zh: "木材", en: "Wood and timber" },
      plain: { zh: "实木、工程木或竹材的建筑立面或结构", en: "Solid timber, engineered wood, or bamboo in facade or structure" },
      professionalTerms: ["mass timber", "CLT", "glulam", "wood cladding", "bamboo structure"],
      promptFragment: {
        zh: "木材立面或木结构，木纹肌理温润自然，蜂蜜色至深棕色调，光线下木香氛围浓郁，生态感强",
        en: "timber facade or wooden structure with warm natural grain texture, honey-to-deep-brown tones, sun-warmed wood atmosphere, strong sense of ecological warmth",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:steel_frame",
      version: "0.1.0",
      label: { zh: "钢铁结构", en: "Steel frame" },
      plain: { zh: "外露钢铁骨架或钢板立面的建筑", en: "Exposed steel skeleton or steel panel cladding" },
      professionalTerms: ["structural steel", "steel frame", "Cor-Ten steel", "iron lattice"],
      promptFragment: {
        zh: "钢铁结构建筑，外露钢梁钢柱或锈色科顿钢板，工业美感，精密焊接节点，硬朗阳刚的材料语言",
        en: "steel-frame building with exposed steel beams and columns or weathering Cor-Ten steel panels, industrial aesthetic, precision-welded joints, hard and masculine material language",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:brick",
      version: "0.1.0",
      label: { zh: "砖砌", en: "Brick" },
      plain: { zh: "红砖、清水砖或彩砖的砌筑立面", en: "Red brick, exposed brick, or patterned brick facade" },
      professionalTerms: ["brick masonry", "flemish bond", "herringbone brick", "terracotta"],
      promptFragment: {
        zh: "砖砌立面，红砖或清水砖纹理温暖亲切，砌缝工艺精致，阳光下产生丰富的明暗层次，历史街区质感",
        en: "brick facade with warm red or exposed brick texture, fine mortar joint craftsmanship, rich light-and-shadow layering in sunlight, textural quality of a historic urban block",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:marble",
      version: "0.1.0",
      label: { zh: "大理石", en: "Marble" },
      plain: { zh: "大理石或花岗岩石材立面或内饰", en: "Marble or granite stone cladding on facade or interior" },
      professionalTerms: ["marble cladding", "granite", "polished stone", "veined marble"],
      promptFragment: {
        zh: "大理石立面，天然云纹脉络清晰，高光泽或哑光打磨，冷峻优雅，奢华感与永恒感并存",
        en: "marble cladding with natural veining clearly visible, high-polish or matte finish, cool and elegant, luxury and timelessness coexisting",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:copper_patina",
      version: "0.1.0",
      label: { zh: "铜板/铜绿", en: "Copper with patina" },
      plain: { zh: "铜板屋顶或立面，表面形成氧化铜绿色", en: "Copper roof or cladding with oxidized green patina surface" },
      professionalTerms: ["copper cladding", "patina", "verdigris", "weathered copper"],
      promptFragment: {
        zh: "铜板屋顶或立面，从金棕铜色渐变为青绿铜绿，沧桑时光痕迹，宝贵的天然氧化肌理",
        en: "copper roof or cladding ranging from warm golden-brown to blue-green verdigris patina, carrying the marks of time — precious natural oxidation texture",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:ceramic_tile",
      version: "0.1.0",
      label: { zh: "瓷砖/马赛克", en: "Ceramic tile and mosaic" },
      plain: { zh: "手工瓷砖、马赛克或彩绘陶砖覆盖的立面", en: "Handmade tile, mosaic, or painted ceramic tile covering the facade" },
      professionalTerms: ["azulejo", "mosaic tile", "terracotta tile", "geometric tile pattern"],
      promptFragment: {
        zh: "瓷砖或马赛克立面，色彩斑斓的几何图案，手工质感细腻，光线下釉面泛光，地中海或伊斯兰风情",
        en: "ceramic tile or mosaic facade with colorful geometric patterns, fine handcrafted texture, glazed surface shimmering in light — Mediterranean or Islamic character",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_arch_material:mixed_modern",
      version: "0.1.0",
      label: { zh: "现代混合材料", en: "Mixed modern materials" },
      plain: { zh: "玻璃、混凝土、金属板等多种当代材料并置", en: "Multiple contemporary materials including glass, concrete, and metal panels juxtaposed" },
      professionalTerms: ["composite facade", "mixed-material cladding", "metal panel", "GFRC"],
      promptFragment: {
        zh: "现代混合材料立面，玻璃、混凝土、金属板与天然石材的精妙组合，材质对比强烈，层次丰富",
        en: "modern mixed-material facade combining glass, concrete, metal panels, and natural stone in a sophisticated composition — strong material contrast and rich layering",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
