import type { OptionSet } from "../../types";

/**
 * P4: Animal breed vocabulary — common dog and cat breeds well-represented in
 * T2I training data. Sourced from Stanford Dogs 120 taxonomy and Danbooru
 * species tags; subset selected for T2I controllability and coverage.
 * Scoped to image_subject:pet_animal and image_subject:wildlife via gradient.
 */
export const imageAnimalBreedOptions: OptionSet = {
  id: "image_animal_breed",
  version: "0.1.0",
  label: { zh: "品种", en: "Breed" },
  categories: [
    {
      id: "cat:image_animal_breed:dog",
      label: { zh: "狗", en: "Dog" },
      optionIds: [
        "image_animal_breed:golden_retriever",
        "image_animal_breed:labrador",
        "image_animal_breed:husky",
        "image_animal_breed:corgi",
        "image_animal_breed:poodle",
        "image_animal_breed:shiba_inu",
        "image_animal_breed:german_shepherd",
        "image_animal_breed:border_collie",
        "image_animal_breed:samoyed",
        "image_animal_breed:french_bulldog",
        "image_animal_breed:dachshund",
        "image_animal_breed:pomeranian",
      ],
    },
    {
      id: "cat:image_animal_breed:cat",
      label: { zh: "猫", en: "Cat" },
      optionIds: [
        "image_animal_breed:british_shorthair",
        "image_animal_breed:persian",
        "image_animal_breed:maine_coon",
        "image_animal_breed:ragdoll",
        "image_animal_breed:scottish_fold",
        "image_animal_breed:siamese",
        "image_animal_breed:bengal",
        "image_animal_breed:orange_tabby",
      ],
    },
  ],
  options: [
    // ── Dogs ─────────────────────────────────────────────────────────────────
    {
      id: "image_animal_breed:golden_retriever",
      version: "0.1.0",
      label: { zh: "金毛寻回犬", en: "Golden Retriever" },
      plain: { zh: "金毛犬，金色长毛", en: "Golden retriever with golden long fur" },
      professionalTerms: ["golden retriever", "golden dog"],
      promptFragment: {
        zh: "金毛寻回犬，金色浓密长毛，温顺友善的面部表情",
        en: "golden retriever with dense golden coat and gentle friendly expression",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:labrador",
      version: "0.1.0",
      label: { zh: "拉布拉多", en: "Labrador" },
      plain: { zh: "拉布拉多，短毛体型大", en: "Labrador with short coat, large build" },
      professionalTerms: ["labrador retriever", "lab dog"],
      promptFragment: {
        zh: "拉布拉多寻回犬，短而光滑的毛色（黄/黑/巧克力），宽厚胸膛",
        en: "labrador retriever with short smooth coat (yellow/black/chocolate), broad chest and sturdy build",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:husky",
      version: "0.1.0",
      label: { zh: "哈士奇", en: "Husky" },
      plain: { zh: "哈士奇，双色双瞳雪橇犬", en: "Husky, sled dog with bicolor eyes" },
      professionalTerms: ["Siberian husky", "husky dog"],
      promptFragment: {
        zh: "西伯利亚哈士奇，黑白双色厚毛，蓝色或杂色眼睛，面部面具花纹",
        en: "Siberian husky with thick black-and-white coat, blue or bi-color eyes and characteristic facial mask",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:corgi",
      version: "0.1.0",
      label: { zh: "柯基", en: "Corgi" },
      plain: { zh: "柯基，短腿大耳红棕色犬", en: "Corgi with short legs and large ears" },
      professionalTerms: ["Pembroke Welsh corgi", "corgi"],
      promptFragment: {
        zh: "彭布罗克威尔士柯基，短腿宽耳，红棕色与白色双色被毛，圆润可爱的臀部",
        en: "Pembroke Welsh corgi with short legs, large upright ears, red-and-white bicolor coat and adorable round rump",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:poodle",
      version: "0.1.0",
      label: { zh: "贵宾犬", en: "Poodle" },
      plain: { zh: "贵宾犬，卷毛优雅", en: "Poodle with curly elegant coat" },
      professionalTerms: ["poodle", "toy poodle", "standard poodle"],
      promptFragment: {
        zh: "贵宾犬，浓密卷曲的被毛，优雅的头部轮廓，聪颖的眼神",
        en: "poodle with dense curly coat, elegant head profile and intelligent bright eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:shiba_inu",
      version: "0.1.0",
      label: { zh: "柴犬", en: "Shiba Inu" },
      plain: { zh: "柴犬，日本小型犬，卷尾", en: "Shiba Inu, Japanese small dog with curled tail" },
      professionalTerms: ["Shiba Inu", "shiba dog"],
      promptFragment: {
        zh: "柴犬，橙红色与奶油色双色被毛，卷翘的尾巴，fox-like 面孔，清晰的双眉",
        en: "Shiba Inu with orange-red and cream bicolor coat, curled tail, fox-like face and distinct brow markings",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:german_shepherd",
      version: "0.1.0",
      label: { zh: "德国牧羊犬", en: "German Shepherd" },
      plain: { zh: "德牧，黑背棕腿工作犬", en: "German shepherd, black saddle working dog" },
      professionalTerms: ["German shepherd", "Alsatian"],
      promptFragment: {
        zh: "德国牧羊犬，黑色马鞍形背部与棕褐色四肢，挺拔的耳朵，专注有神的眼睛",
        en: "German shepherd with black saddle marking, tan legs, upright ears and focused intelligent eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:border_collie",
      version: "0.1.0",
      label: { zh: "边境牧羊犬", en: "Border Collie" },
      plain: { zh: "边牧，黑白毛色高智商牧羊犬", en: "Border collie, black-and-white herding dog" },
      professionalTerms: ["border collie", "herding dog"],
      promptFragment: {
        zh: "边境牧羊犬，黑白双色中长毛，聪颖专注的眼神，敏捷轻盈的身形",
        en: "border collie with black-and-white medium-length coat, keen intelligent gaze and agile athletic build",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:samoyed",
      version: "0.1.0",
      label: { zh: "萨摩耶", en: "Samoyed" },
      plain: { zh: "萨摩耶，纯白厚毛笑脸犬", en: "Samoyed, pure white fluffy smiling dog" },
      professionalTerms: ["Samoyed", "samoyed dog"],
      promptFragment: {
        zh: "萨摩耶，纯白厚实的双层被毛，上翘的嘴角呈现标志性微笑，圆润的黑色眼睛",
        en: "Samoyed with pure white thick double coat, upturned mouth corners in the signature smile and round dark eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:french_bulldog",
      version: "0.1.0",
      label: { zh: "法国斗牛犬", en: "French Bulldog" },
      plain: { zh: "法斗，蝙蝠耳小短腿", en: "French bulldog with bat ears and compact build" },
      professionalTerms: ["French bulldog", "Frenchie"],
      promptFragment: {
        zh: "法国斗牛犬，宽大蝙蝠耳，扁平短鼻，紧实矮壮身形，短光滑被毛",
        en: "French bulldog with wide bat ears, flat short snout, compact stocky body and short smooth coat",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:dachshund",
      version: "0.1.0",
      label: { zh: "腊肠犬", en: "Dachshund" },
      plain: { zh: "腊肠犬，长身短腿", en: "Dachshund with long body and short legs" },
      professionalTerms: ["dachshund", "sausage dog", "wiener dog"],
      promptFragment: {
        zh: "腊肠犬，长躯短腿的独特比例，长耷耳朵，光滑或长毛被毛（红棕/黑棕）",
        en: "dachshund with characteristically long body and short legs, droopy long ears and smooth or long coat in red or black-and-tan",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:pomeranian",
      version: "0.1.0",
      label: { zh: "博美", en: "Pomeranian" },
      plain: { zh: "博美，蓬松小圆球狐狸脸", en: "Pomeranian, fluffy fox-faced small dog" },
      professionalTerms: ["Pomeranian", "pom dog"],
      promptFragment: {
        zh: "博美犬，极度蓬松的双层毛球形轮廓，狐狸般的尖脸，明亮好奇的小眼睛",
        en: "Pomeranian with extremely fluffy double coat in a round puff silhouette, fox-like pointed face and bright curious eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    // ── Cats ─────────────────────────────────────────────────────────────────
    {
      id: "image_animal_breed:british_shorthair",
      version: "0.1.0",
      label: { zh: "英国短毛猫", en: "British Shorthair" },
      plain: { zh: "英短，圆脸厚腮大眼蓝猫", en: "British shorthair, round-faced plush blue cat" },
      professionalTerms: ["British shorthair", "British blue cat"],
      promptFragment: {
        zh: "英国短毛猫，圆润宽阔的面庞，丰厚短密的被毛（蓝灰/金渐层/虎斑），圆大铜色眼睛",
        en: "British shorthair with round broad face, plush short dense coat (blue/golden-shaded/tabby) and large copper-colored eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:persian",
      version: "0.1.0",
      label: { zh: "波斯猫", en: "Persian" },
      plain: { zh: "波斯猫，扁鼻长毛优雅", en: "Persian with flat face and long silky fur" },
      professionalTerms: ["Persian cat", "flat-face cat"],
      promptFragment: {
        zh: "波斯猫，扁平鼻梁，极长丝滑被毛，优雅慵懒的仪态，大而圆的眼睛",
        en: "Persian cat with flat pushed-in nose, long silky flowing coat, graceful languid posture and large round eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:maine_coon",
      version: "0.1.0",
      label: { zh: "缅因猫", en: "Maine Coon" },
      plain: { zh: "缅因猫，大型长毛耳簇猫", en: "Maine coon, large long-haired cat with ear tufts" },
      professionalTerms: ["Maine coon", "Maine cat"],
      promptFragment: {
        zh: "缅因猫，大型长毛，耳尖毛簇，浓密蓬松的尾巴，野性而威严的面部轮廓",
        en: "Maine coon with large long-haired build, lynx-like ear tufts, full bushy tail and wild majestic facial features",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:ragdoll",
      version: "0.1.0",
      label: { zh: "布偶猫", en: "Ragdoll" },
      plain: { zh: "布偶猫，蓝眼重色点长毛", en: "Ragdoll with blue eyes and colorpoint coat" },
      professionalTerms: ["ragdoll cat", "colorpoint longhair"],
      promptFragment: {
        zh: "布偶猫，蓬松中长毛（重色点花色），深蓝色大眼睛，温顺柔软的肢体语言",
        en: "ragdoll cat with semi-long plush coat in colorpoint pattern, deep blue eyes and docile relaxed body language",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:scottish_fold",
      version: "0.1.0",
      label: { zh: "苏格兰折耳猫", en: "Scottish Fold" },
      plain: { zh: "折耳猫，耳朵向前折叠圆脸", en: "Scottish fold with forward-folded ears and round face" },
      professionalTerms: ["Scottish fold", "fold-ear cat"],
      promptFragment: {
        zh: "苏格兰折耳猫，向前折叠的小耳朵，圆润娃娃脸，宽大圆眼睛",
        en: "Scottish fold with characteristic forward-folded small ears, round owl-like face and wide round eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:siamese",
      version: "0.1.0",
      label: { zh: "暹罗猫", en: "Siamese" },
      plain: { zh: "暹罗猫，深色重点色蓝眼", en: "Siamese with colorpoint markings and blue eyes" },
      professionalTerms: ["Siamese cat", "Thai cat"],
      promptFragment: {
        zh: "暹罗猫，奶油色躯体配深褐色面部/耳/四肢重点色，蓝宝石色杏仁眼，纤细修长身形",
        en: "Siamese cat with cream body and dark seal-point markings on face/ears/legs, sapphire-blue almond eyes and slender elegant build",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:bengal",
      version: "0.1.0",
      label: { zh: "孟加拉豹猫", en: "Bengal" },
      plain: { zh: "孟加拉猫，豹纹短毛野性", en: "Bengal with leopard-like spotted coat" },
      professionalTerms: ["Bengal cat", "leopard cat hybrid"],
      promptFragment: {
        zh: "孟加拉猫，闪亮金棕色底色配暗色豹纹斑点，短而光亮的被毛，肌肉感强健的身形",
        en: "Bengal cat with shimmering golden-brown coat and dark leopard-like rosette spots, short glossy fur and muscular athletic build",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
    {
      id: "image_animal_breed:orange_tabby",
      version: "0.1.0",
      label: { zh: "橘猫", en: "Orange Tabby" },
      plain: { zh: "橘猫，经典橘色虎斑条纹", en: "Orange tabby with classic ginger stripes" },
      professionalTerms: ["orange tabby cat", "ginger tabby", "marmalade cat"],
      promptFragment: {
        zh: "橘色虎斑猫，鲜亮橙红色毛色配深棕色虎斑条纹，胖嘟嘟的圆脸，金色眼睛",
        en: "orange tabby cat with bright ginger coat and deep tabby stripes, chubby round face and golden eyes",
      },
      riskHint: { zh: "", en: "" },
      appliesTo: ["generic_image"],
    },
  ],
};
