// AUTO-GENERATED by .research/scripts/gen-audit-model.mjs — do not edit by hand.
// Source: Hermes catalog audit (validated 139/139 real ids by validate-audit.mjs).
// Regenerate: node .research/scripts/gen-audit-model.mjs
//
// Only the fully-real-id parts of the audit live here. The subject-rooted
// `branches` model is deferred to Slice 2 (needs proposed dimensions built first).

/** A directional relation between two option ids in different dimensions. */
export interface OptionConflict {
  a: string;
  b: string;
  /** "conflict" = hard (hide), "caution" = soft (warn but allow). */
  relation: "conflict" | "caution";
  reason: string;
  confidence?: number;
}

/** A soft recommendation: when `from` is selected, `to` is a likely companion. */
export interface OptionAssociation {
  from: string;
  to: string;
  /** 0–1 prior strength. Mostly semantic (model intuition), not measured. */
  strength: number;
  reason: string;
}

/** Free-text → primary-type routing signals for the entry step (Slice 2 UI). */
export interface EntryRoute {
  primaryType: string;
  signals: string[];
  note?: string;
}

export const OPTION_CONFLICTS: OptionConflict[] = [
  {
    "a": "image_framing:wide_shot",
    "b": "image_camera:85mm_portrait",
    "relation": "conflict",
    "reason": "85mm 人像镜头视角窄，容纳不下全身远景",
    "confidence": 0.85
  },
  {
    "a": "image_framing:extreme_wide",
    "b": "image_camera:85mm_portrait",
    "relation": "conflict",
    "reason": "85mm 长焦无法表现极远景",
    "confidence": 0.9
  },
  {
    "a": "image_framing:wide_shot",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "微距镜头只能极近拍摄，与远景矛盾",
    "confidence": 0.9
  },
  {
    "a": "image_framing:medium_shot",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "微距与中景矛盾",
    "confidence": 0.85
  },
  {
    "a": "image_framing:extreme_wide",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "微距与极远景矛盾",
    "confidence": 0.9
  },
  {
    "a": "image_framing:extreme_wide",
    "b": "image_camera:200mm_telephoto",
    "relation": "caution",
    "reason": "200mm 长焦做极远景需极远拍摄距离",
    "confidence": 0.6
  },
  {
    "a": "image_framing:close_up",
    "b": "image_camera:35mm_wide",
    "relation": "caution",
    "reason": "35mm 广角近距拍人脸会透视变形",
    "confidence": 0.6
  },
  {
    "a": "image_camera:35mm_wide",
    "b": "image_camera:50mm_standard",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：35mm 与 50mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:35mm_wide",
    "b": "image_camera:85mm_portrait",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：35mm 与 85mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:35mm_wide",
    "b": "image_camera:200mm_telephoto",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：35mm 与 200mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:35mm_wide",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：35mm 与微距互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:50mm_standard",
    "b": "image_camera:85mm_portrait",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：50mm 与 85mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:50mm_standard",
    "b": "image_camera:200mm_telephoto",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：50mm 与 200mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:50mm_standard",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：50mm 与微距互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:85mm_portrait",
    "b": "image_camera:200mm_telephoto",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：85mm 与 200mm 互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:85mm_portrait",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：85mm 与微距互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:200mm_telephoto",
    "b": "image_camera:macro_lens",
    "relation": "conflict",
    "reason": "一次拍摄只用一个焦段：200mm 与微距互斥",
    "confidence": 0.9
  },
  {
    "a": "image_camera:wide_aperture_bokeh",
    "b": "image_camera:deep_dof",
    "relation": "conflict",
    "reason": "浅景深（大光圈虚化）与深景深（全清晰）矛盾",
    "confidence": 0.9
  },
  {
    "a": "image_subject:single_person",
    "b": "image_scene:starry_cosmos",
    "relation": "caution",
    "reason": "单人肖像在星空背景中需要特殊合成处理，普通模型容易丢失人物细节",
    "confidence": 0.7
  },
  {
    "a": "image_subject:hero_product",
    "b": "image_scene:natural_landscape",
    "relation": "caution",
    "reason": "产品主角放在自然风景中容易被环境淹没",
    "confidence": 0.8
  },
  {
    "a": "image_lighting:midday_harsh",
    "b": "image_framing:close_up",
    "relation": "caution",
    "reason": "正午强光+特写会暴露皮肤瑕疵",
    "confidence": 0.7
  },
  {
    "a": "image_art_style:minimalist",
    "b": "image_detail_level:hyper_detailed",
    "relation": "conflict",
    "reason": "极简风格追求'少'，8K极致细节追求'多'——方向矛盾",
    "confidence": 0.9
  },
  {
    "a": "image_art_style:oil_painting",
    "b": "image_post_processing:chromatic_aberration",
    "relation": "caution",
    "reason": "油画风格不应有色差（镜头瑕疵）",
    "confidence": 0.8
  },
  {
    "a": "image_mood:nostalgic_vintage",
    "b": "image_art_style:cyberpunk",
    "relation": "caution",
    "reason": "怀旧复古vs赛博朋克方向相反",
    "confidence": 0.75
  },
  {
    "a": "image_scene:indoor_setting",
    "b": "image_lighting:colored_gel",
    "relation": "conflict",
    "reason": "室内场景+彩色灯光：仅当刻意营造派对/夜店氛围时成立，日常室内场景不自然",
    "confidence": 0.9
  },
  {
    "a": "image_time_season:midnight",
    "b": "image_lighting:midday_harsh",
    "relation": "conflict",
    "reason": "深夜不可能有正午强光",
    "confidence": 0.95
  },
  {
    "a": "image_subject:food_beverage",
    "b": "image_scene:starry_cosmos",
    "relation": "caution",
    "reason": "食物在星空中非常不自然",
    "confidence": 0.8
  },
  {
    "a": "image_art_style:line_art",
    "b": "image_post_processing:hdr",
    "relation": "conflict",
    "reason": "线条画是单色/简约，HDR是高动态范围——机制矛盾",
    "confidence": 0.85
  },
  {
    "a": "image_color_palette:monochrome",
    "b": "image_color_palette:vibrant",
    "relation": "conflict",
    "reason": "黑白/灰度vs鲜艳饱和——同维度内互斥",
    "confidence": 0.95
  },
  {
    "a": "image_subject:silhouette_figure",
    "b": "image_constraints:no_bad_anatomy",
    "relation": "caution",
    "reason": "剪影不露面部细节，anatomy约束意义不大",
    "confidence": 0.7
  }
];

export const OPTION_ASSOCIATIONS: OptionAssociation[] = [
  {
    "from": "image_use_case:avatar",
    "to": "image_subject:single_person",
    "strength": 0.95,
    "reason": "头像几乎必然是单人"
  },
  {
    "from": "image_use_case:product_photo",
    "to": "image_subject:hero_product",
    "strength": 0.9,
    "reason": "产品图的主体就是产品"
  },
  {
    "from": "image_use_case:ecommerce_main",
    "to": "image_subject:hero_product",
    "strength": 0.95,
    "reason": "电商主图=产品白底图"
  },
  {
    "from": "image_use_case:menu",
    "to": "image_subject:food_beverage",
    "strength": 0.9,
    "reason": "菜单配图主体是食物"
  },
  {
    "from": "image_use_case:thumbnail",
    "to": "image_subject:single_person",
    "strength": 0.7,
    "reason": "YouTube缩略图常用人物"
  },
  {
    "from": "image_use_case:wallpaper",
    "to": "image_subject:natural_landscape",
    "strength": 0.6,
    "reason": "壁纸常用风景"
  },
  {
    "from": "image_use_case:product_photo",
    "to": "image_scene:white_bg",
    "strength": 0.85,
    "reason": "产品图常用白底"
  },
  {
    "from": "image_use_case:ecommerce_main",
    "to": "image_scene:white_bg",
    "strength": 0.9,
    "reason": "电商主图标准白底"
  },
  {
    "from": "image_use_case:avatar",
    "to": "image_scene:solid_color",
    "strength": 0.7,
    "reason": "头像常用纯色背景"
  },
  {
    "from": "image_subject:single_person",
    "to": "image_scene:studio_env",
    "strength": 0.6,
    "reason": "人像常用影棚环境"
  },
  {
    "from": "image_subject:single_person",
    "to": "image_scene:indoor_setting",
    "strength": 0.5,
    "reason": "人像也常用室内场景"
  },
  {
    "from": "image_subject:natural_landscape",
    "to": "image_scene:natural_landscape",
    "strength": 0.9,
    "reason": "风景主体自然配风景背景"
  },
  {
    "from": "image_subject:pet_animal",
    "to": "image_scene:indoor_setting",
    "strength": 0.6,
    "reason": "宠物常在室内拍"
  },
  {
    "from": "image_subject:wildlife",
    "to": "image_scene:natural_landscape",
    "strength": 0.85,
    "reason": "野生动物在自然环境中"
  },
  {
    "from": "image_subject:single_person",
    "to": "image_lighting:window_soft",
    "strength": 0.6,
    "reason": "人像常用窗边柔光"
  },
  {
    "from": "image_subject:single_person",
    "to": "image_lighting:golden_hour",
    "strength": 0.5,
    "reason": "人像也常用黄金时刻"
  },
  {
    "from": "image_subject:hero_product",
    "to": "image_lighting:studio_clean",
    "strength": 0.8,
    "reason": "产品图常用影棚光"
  },
  {
    "from": "image_subject:character_design",
    "to": "image_art_style:anime_manga",
    "strength": 0.7,
    "reason": "角色设计常用动漫风格"
  },
  {
    "from": "image_mood:warm_cozy",
    "to": "image_lighting:warm_lamp",
    "strength": 0.7,
    "reason": "温馨氛围常用暖黄灯光"
  },
  {
    "from": "image_mood:dark_moody",
    "to": "image_lighting:low_key",
    "strength": 0.8,
    "reason": "暗黑氛围用低调光"
  },
  {
    "from": "image_mood:futuristic_scifi",
    "to": "image_lighting:neon_light",
    "strength": 0.75,
    "reason": "科幻氛围常用霓虹光"
  },
  {
    "from": "image_mood:romantic_dreamy",
    "to": "image_lighting:golden_hour",
    "strength": 0.7,
    "reason": "浪漫氛围常用黄金时刻"
  },
  {
    "from": "image_mood:futuristic_scifi",
    "to": "image_art_style:cyberpunk",
    "strength": 0.8,
    "reason": "科幻氛围→赛博朋克风格"
  },
  {
    "from": "image_mood:nostalgic_vintage",
    "to": "image_art_style:vintage_retro",
    "strength": 0.85,
    "reason": "怀旧氛围→复古风格"
  },
  {
    "from": "image_mood:playful_cute",
    "to": "image_art_style:korean_manhwa",
    "strength": 0.7,
    "reason": "可爱氛围→Q版风格"
  },
  {
    "from": "image_lighting:neon_light",
    "to": "image_art_style:cyberpunk",
    "strength": 0.75,
    "reason": "霓虹光→赛博朋克"
  },
  {
    "from": "image_use_case:social_media_post",
    "to": "image_aspect_ratio:square_1_1",
    "strength": 0.7,
    "reason": "社媒配图常用1:1"
  },
  {
    "from": "image_use_case:thumbnail",
    "to": "image_aspect_ratio:landscape_16_9",
    "strength": 0.85,
    "reason": "YouTube缩略图标准16:9"
  },
  {
    "from": "image_use_case:wallpaper",
    "to": "image_aspect_ratio:portrait_9_16",
    "strength": 0.7,
    "reason": "手机壁纸常用9:16"
  },
  {
    "from": "image_subject:hero_product",
    "to": "image_composition:centered",
    "strength": 0.7,
    "reason": "产品图常用居中构图"
  },
  {
    "from": "image_subject:single_person",
    "to": "image_composition:rule_of_thirds",
    "strength": 0.6,
    "reason": "人像常用三分法"
  },
  {
    "from": "image_camera_angle:macro_view",
    "to": "image_subject:botanical_flora",
    "strength": 0.7,
    "reason": "微距常拍花卉"
  },
  {
    "from": "image_camera_angle:aerial_view",
    "to": "image_subject:natural_landscape",
    "strength": 0.7,
    "reason": "鸟瞰常用于风景"
  }
];

export const ENTRY_ROUTES: EntryRoute[] = [
  {
    "primaryType": "人像",
    "signals": [
      "人",
      "girl",
      "woman",
      "man",
      "portrait",
      "selfie",
      "头像",
      "写真",
      "帅哥",
      "美女",
      "人物",
      "角色",
      "character",
      "person",
      "people",
      "群像",
      "合照",
      "朋友",
      "情侣",
      "宝宝",
      "孩子",
      "老人"
    ],
    "note": "人物相关名词/代词/外貌词→路由。模糊时追问。"
  },
  {
    "primaryType": "产品/静物",
    "signals": [
      "产品",
      "product",
      "手机",
      "电脑",
      "耳机",
      "手表",
      "包",
      "首饰",
      "化妆品",
      "瓶子",
      "logo",
      "图标",
      "物品",
      "东西",
      "gadget",
      "device",
      "jewelry",
      "bottle",
      "car",
      "汽车",
      "摩托车"
    ],
    "note": "具体物品名称或泛称→路由。电商用语也归此类。"
  },
  {
    "primaryType": "场景/氛围",
    "signals": [
      "风景",
      "landscape",
      "城市",
      "city",
      "天空",
      "sky",
      "星空",
      "starry",
      "室内",
      "interior",
      "房间",
      "room",
      "建筑",
      "building",
      "街景",
      "street",
      "海",
      "ocean",
      "山",
      "mountain",
      "森林",
      "forest",
      "日落",
      "sunset",
      "宇宙",
      "cosmos",
      "氛围",
      "atmosphere",
      "moody"
    ],
    "note": "主体即场景或描述环境/氛围时路由。'一个人在海边'→人像。"
  },
  {
    "primaryType": "动物",
    "signals": [
      "猫",
      "cat",
      "狗",
      "dog",
      "宠物",
      "pet",
      "动物",
      "animal",
      "鸟",
      "bird",
      "鱼",
      "fish",
      "马",
      "horse",
      "狮子",
      "lion",
      "熊猫",
      "panda",
      "兔",
      "rabbit",
      "仓鼠",
      "hamster"
    ],
    "note": "动物名称→路由。'人和猫'→人像。"
  },
  {
    "primaryType": "食物/饮品",
    "signals": [
      "食物",
      "food",
      "蛋糕",
      "cake",
      "咖啡",
      "coffee",
      "茶",
      "tea",
      "菜",
      "dish",
      "甜点",
      "dessert",
      "冰淇淋",
      "ice cream",
      "面包",
      "bread",
      "寿司",
      "sushi",
      "牛排",
      "steak",
      "饮品",
      "drink",
      "鸡尾酒",
      "cocktail",
      "摆盘",
      "plating"
    ],
    "note": "食物/饮品名称或烹饪词汇→路由。"
  }
];

/** Option ids that conflict with any of the given selected ids.
 *  By default only "hard" conflicts (relation==="conflict") block.
 *  Pass {includeCaution:true} to also block "caution" relations — used
 *  by the auto-fill pipeline to be maximally conservative. */
export function conflictIdsFor(
  selectedIds: Iterable<string>,
  opts?: { includeCaution?: boolean },
): Set<string> {
  const selected = new Set(selectedIds);
  const blocked = new Set<string>();
  for (const c of OPTION_CONFLICTS) {
    if (c.relation === "conflict" || (opts?.includeCaution && c.relation === "caution")) {
      if (selected.has(c.a)) blocked.add(c.b);
      if (selected.has(c.b)) blocked.add(c.a);
    }
  }
  return blocked;
}

/** Option ids that hard-conflict with any of the given selected ids. */
export function hardConflictIdsFor(selectedIds: Iterable<string>): Set<string> {
  return conflictIdsFor(selectedIds, { includeCaution: false });
}

/** Option ids recommended (associated) given the currently selected ids —
 *  directional: from `from` (selected) to `to`. Used for "推荐" badges. */
export function suggestedIdsFor(selectedIds: Iterable<string>): Set<string> {
  const selected = new Set(selectedIds);
  const out = new Set<string>();
  for (const a of OPTION_ASSOCIATIONS) {
    if (selected.has(a.from) && !selected.has(a.to)) out.add(a.to);
  }
  return out;
}
