// AUTO-GENERATED by .research/scripts/gen-gradient.mjs — do not edit by hand.
// Source: .research/out/dimension-gradient.json (validated against 21 real questionIds + catalog options).
// Regenerate: node .research/scripts/gen-gradient.mjs


export type Precision = "simple" | "standard" | "detailed";

export interface GradientItem {
  questionId: string;
  rationale?: string;
  corpusFreq?: number | null;
  source: string;
}

export interface PrecompiledCondition {
  dimension: string;
  op: "in";
  values: string[];  // full-prefix option ids: image_<dim>:<suffix>
}

export interface ConditionalEntry {
  questionId: string;
  condition: PrecompiledCondition;
  minPrecision: Precision | "any";
  tierWhenActive: "suppress" | "activate";
  source: string;
}

export interface PrimaryTypeGradient {
  type: string;
  essential: GradientItem[];
  secondary: GradientItem[];
  tertiary: GradientItem[];
  conditional: ConditionalEntry[];
  order: string[];
}

export interface GradientData {
  shared: {
    essential: GradientItem[];
    tertiary: GradientItem[];
  };
  primaryTypes: PrimaryTypeGradient[];
}

export const GRADIENT: GradientData = {
  "shared": {
    "essential": [
      {
        "questionId": "aspect_ratio",
        "source": "audit:always"
      },
      {
        "questionId": "constraints",
        "source": "audit:always"
      }
    ],
    "tertiary": [
      {
        "questionId": "detail_level",
        "source": "audit:always(倒数第二步)"
      },
      {
        "questionId": "use_case",
        "source": "audit:always(入口路由后)"
      }
    ]
  },
  "primaryTypes": [
    {
      "type": "人像",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "主体=人物类型，首轮必问",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "framing",
          "rationale": "景别控深枢纽，决定后续细节深度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景/背景",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线对人像质感影响极大",
          "corpusFreq": 580,
          "source": "audit:always"
        },
        {
          "questionId": "color_palette",
          "rationale": "维护者要求色调早问；现版每次都问",
          "corpusFreq": 103,
          "source": "maintainer-override"
        }
      ],
      "secondary": [
        {
          "questionId": "camera",
          "rationale": "镜头焦段决定透视/景深，audit 人像 always",
          "corpusFreq": 403,
          "source": "audit:always(demoted:非首问核心,降simple动线)"
        },
        {
          "questionId": "art_style",
          "rationale": "画风影响整体视觉；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "pose",
          "rationale": "姿态/动作；audit 人像 always 但 framing=close_up 时 suppress",
          "corpusFreq": 133,
          "source": "audit:always"
        },
        {
          "questionId": "outfit",
          "rationale": "着装/造型；framing=close_up 时 suppress",
          "corpusFreq": 187,
          "source": "audit:always"
        },
        {
          "questionId": "hair",
          "rationale": "发型；特写/半身时有意义",
          "corpusFreq": 50,
          "source": "audit:always"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [
        {
          "questionId": "pose",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:close_up"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        },
        {
          "questionId": "outfit",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:close_up"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        },
        {
          "questionId": "hair",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:wide_shot",
              "image_framing:extreme_wide"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        }
      ],
      "order": [
        "subject",
        "framing",
        "scene",
        "lighting",
        "camera",
        "color_palette",
        "art_style",
        "mood",
        "pose",
        "outfit",
        "hair",
        "post_processing"
      ]
    },
    {
      "type": "产品/静物",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "产品类型决定后续材质/场景选择",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "product_material",
          "rationale": "材质是产品图核心差异化维度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "拍摄角度对产品展示至关重要；audit 产品 always",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "背景/环境",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线影响产品质感呈现",
          "corpusFreq": 580,
          "source": "audit:always"
        },
        {
          "questionId": "color_palette",
          "rationale": "维护者要求色调早问",
          "corpusFreq": 103,
          "source": "maintainer-override"
        }
      ],
      "secondary": [
        {
          "questionId": "composition",
          "rationale": "构图对产品摆放很重要；audit precision>=medium",
          "corpusFreq": 248,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "art_style",
          "rationale": "渲染风格",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "product_material",
        "camera",
        "scene",
        "lighting",
        "color_palette",
        "composition",
        "art_style",
        "post_processing"
      ]
    },
    {
      "type": "场景/氛围",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "场景类型（风景/城市/星空/室内/建筑）",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景细节/特征",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "time_season",
          "rationale": "时间/季节对场景影响大",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "weather",
          "rationale": "天气是场景氛围核心变量",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "镜头/视角（广角/长焦/航拍）",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "audit:always"
        }
      ],
      "secondary": [
        {
          "questionId": "mood",
          "rationale": "场景类型 audit always；氛围驱动型",
          "corpusFreq": 201,
          "source": "audit:always(demoted:与其他类型一致,mood不入essential)"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调；audit precision>=medium",
          "corpusFreq": 103,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "art_style",
          "rationale": "画风",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "composition",
          "rationale": "构图",
          "corpusFreq": 248,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "scene",
        "time_season",
        "weather",
        "camera",
        "lighting",
        "mood",
        "color_palette",
        "art_style",
        "composition",
        "post_processing"
      ]
    },
    {
      "type": "动物",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "动物类型（宠物/野生动物）",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "framing",
          "rationale": "景别决定细节深度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景/背景",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "audit:always"
        },
        {
          "questionId": "constraints",
          "rationale": "避免 bad_anatomy/extra_limbs（动物类高频问题）",
          "corpusFreq": null,
          "source": "audit:always"
        }
      ],
      "secondary": [
        {
          "questionId": "art_style",
          "rationale": "画风；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "camera",
          "rationale": "镜头；audit 动物 precision>=medium（非 always）",
          "corpusFreq": 403,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调",
          "corpusFreq": 103,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "framing",
        "scene",
        "lighting",
        "art_style",
        "mood",
        "camera",
        "color_palette",
        "post_processing"
      ]
    },
    {
      "type": "食物/饮品",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "食物类型",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "拍摄角度对食物展示至关重要；audit always",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "背景/环境",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "audit:always"
        },
        {
          "questionId": "color_palette",
          "rationale": "食物色调/摆盘色彩极其重要；maintainer-override",
          "corpusFreq": 103,
          "source": "maintainer-override"
        }
      ],
      "secondary": [
        {
          "questionId": "art_style",
          "rationale": "画风；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "camera",
        "scene",
        "lighting",
        "color_palette",
        "art_style",
        "mood",
        "post_processing"
      ]
    },
    {
      "type": "通用",
      "essential": [
        {
          "questionId": "aspect_ratio",
          "source": "audit:always"
        },
        {
          "questionId": "constraints",
          "source": "audit:always"
        },
        {
          "questionId": "subject",
          "rationale": "主体",
          "corpusFreq": 667,
          "source": "fallback-CORE"
        },
        {
          "questionId": "scene",
          "rationale": "场景",
          "corpusFreq": 860,
          "source": "fallback-CORE"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "fallback-CORE"
        },
        {
          "questionId": "art_style",
          "rationale": "风格",
          "corpusFreq": 435,
          "source": "fallback-CORE"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调",
          "corpusFreq": 103,
          "source": "fallback-CORE"
        }
      ],
      "secondary": [],
      "tertiary": [],
      "conditional": [],
      "order": [
        "subject",
        "scene",
        "lighting",
        "art_style",
        "color_palette"
      ]
    }
  ]
};
