// Originally AUTO-GENERATED by .research/scripts/gen-gradient.mjs.
// Now maintained by hand — do not regenerate without re-applying these patches:
//   • 动物: constraints removed from essential (kept only in shared.essential; dedup)
//   • 动物: "constraints" inserted into order array before aspect_ratio so anatomy
//     constraints appear at step 5 (after lighting) instead of last


export type Precision = "simple" | "standard" | "detailed";

export interface GradientItem {
  questionId: string;
  rationale?: string;
  corpusFreq?: number | null;
  source: string;
  /** See QuestionSchema.scopeToOption — gate this dim on a selected subject option. */
  scopeToOption?: string[];
}

export interface PrecompiledCondition {
  dimension: string;
  op: "in";
  values: string[];  // full-prefix option ids: image_<dim>:<suffix>
}

export interface ConditionalEntry {
  questionId: string;
  condition: PrecompiledCondition;
  minPrecision: Precision | "any";
  tierWhenActive: "suppress" | "activate";
  source: string;
}

export interface PrimaryTypeGradient {
  type: string;
  essential: GradientItem[];
  secondary: GradientItem[];
  tertiary: GradientItem[];
  conditional: ConditionalEntry[];
  order: string[];
}

export interface GradientData {
  shared: {
    essential: GradientItem[];
    tertiary: GradientItem[];
  };
  primaryTypes: PrimaryTypeGradient[];
}

export const GRADIENT: GradientData = {
  "shared": {
    "essential": [
      {
        "questionId": "aspect_ratio",
        "source": "audit:always"
      },
      {
        "questionId": "constraints",
        "source": "audit:always"
      }
    ],
    "tertiary": [
      {
        "questionId": "detail_level",
        "source": "audit:always(倒数第二步)"
      },
      {
        "questionId": "use_case",
        "source": "audit:always(入口路由后)"
      }
    ]
  },
  "primaryTypes": [
    {
      "type": "人像",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "主体=人物类型，首轮必问",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "framing",
          "rationale": "景别控深枢纽，决定后续细节深度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景/背景",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          // P6: portrait expression scoped to single_person / character_design
          "questionId": "portrait_expression",
          "rationale": "P6 人物表情；仅在单人/角色设计主体时激活，近景最有效",
          "corpusFreq": null,
          "source": "redesign:P6:portrait-expression",
          "scopeToOption": [
            "image_subject:single_person",
            "image_subject:character_design"
          ]
        }
      ],
      "secondary": [
        {
          "questionId": "lighting",
          "rationale": "光线对人像质感影响大，但人像分支降级/pro 档（doc §3.3）",
          "corpusFreq": 580,
          "source": "redesign:P2:lighting-demote"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调降级为 secondary（owner decision 3，去除 maintainer-override pin）",
          "corpusFreq": 103,
          "source": "redesign:P2:color-demote"
        },
        {
          "questionId": "camera",
          "rationale": "镜头焦段决定透视/景深，audit 人像 always",
          "corpusFreq": 403,
          "source": "audit:always(demoted:非首问核心,降simple动线)"
        },
        {
          "questionId": "art_style",
          "rationale": "画风影响整体视觉；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "pose",
          "rationale": "姿态/动作；audit 人像 always 但 framing=close_up 时 suppress",
          "corpusFreq": 133,
          "source": "audit:always",
          "scopeToOption": [
            "image_subject:single_person", "image_subject:group_portrait",
            "image_subject:character_design", "image_subject:silhouette_figure"
          ]
        },
        {
          "questionId": "outfit",
          "rationale": "着装/造型；framing=close_up 时 suppress",
          "corpusFreq": 187,
          "source": "audit:always",
          "scopeToOption": [
            "image_subject:single_person", "image_subject:group_portrait",
            "image_subject:character_design"
          ]
        },
        {
          "questionId": "hair",
          "rationale": "发型；特写/半身时有意义",
          "corpusFreq": 50,
          "source": "audit:always",
          "scopeToOption": [
            "image_subject:single_person", "image_subject:group_portrait",
            "image_subject:character_design"
          ]
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [
        {
          "questionId": "pose",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:close_up"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        },
        {
          "questionId": "outfit",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:close_up"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        },
        {
          "questionId": "hair",
          "condition": {
            "dimension": "framing",
            "op": "in",
            "values": [
              "image_framing:wide_shot",
              "image_framing:extreme_wide"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "audit:framingDepthRules"
        }
      ],
      "order": [
        "subject",
        "framing",
        "portrait_expression",
        "scene",
        "lighting",
        "camera",
        "color_palette",
        "art_style",
        "mood",
        "pose",
        "outfit",
        "hair",
        "post_processing"
      ]
    },
    {
      "type": "产品/静物",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "产品类型决定后续材质/场景选择",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "product_material",
          "rationale": "材质是产品图核心差异化维度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "拍摄角度对产品展示至关重要；audit 产品 always",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "背景/环境",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线影响产品质感呈现（产品分支 lighting=essential，doc §3.3）",
          "corpusFreq": 580,
          "source": "audit:always"
        }
      ],
      "secondary": [
        {
          "questionId": "color_palette",
          "rationale": "色调降级为 secondary（owner decision 3；产品 color-lock 风险见 watch-note）",
          "corpusFreq": 103,
          "source": "redesign:P2:color-demote"
        },
        {
          "questionId": "composition",
          "rationale": "构图对产品摆放很重要；audit precision>=medium",
          "corpusFreq": 248,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "art_style",
          "rationale": "渲染风格",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "product_material",
        "camera",
        "scene",
        "lighting",
        "color_palette",
        "composition",
        "art_style",
        "post_processing"
      ]
    },
    {
      "type": "场景/氛围",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "场景类型（风景/城市/星空/室内/建筑）",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景细节/特征",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "time_season",
          "rationale": "时间/季节对场景影响大",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "weather",
          "rationale": "天气是场景氛围核心变量",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "镜头/视角（广角/长焦/航拍）",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "audit:always"
        },
        {
          "questionId": "camera_angle",
          "rationale": "P3 风景视角/机位（航拍/俯视/等距）；仅在风景主体时激活",
          "corpusFreq": null,
          "source": "redesign:P3:landscape-vantage",
          "scopeToOption": [
            "image_subject:natural_landscape",
            "image_subject:cityscape",
            "image_subject:skyscape"
          ]
        },
        {
          "questionId": "arch_style",
          "rationale": "P5 建筑风格（哥特/现代主义/巴洛克等）；仅在建筑主体时激活",
          "corpusFreq": null,
          "source": "redesign:P5:arch-style",
          "scopeToOption": [
            "image_subject:architectural_exterior",
            "image_subject:interior_space"
          ]
        },
        {
          "questionId": "arch_type",
          "rationale": "P5 建筑类型（大教堂/摩天楼/博物馆等）；仅在建筑主体时激活",
          "corpusFreq": null,
          "source": "redesign:P5:arch-type",
          "scopeToOption": [
            "image_subject:architectural_exterior",
            "image_subject:interior_space"
          ]
        },
        {
          "questionId": "arch_material",
          "rationale": "P5 建筑材质（石材/玻璃/混凝土等）；仅在建筑主体时激活",
          "corpusFreq": null,
          "source": "redesign:P5:arch-material",
          "scopeToOption": [
            "image_subject:architectural_exterior",
            "image_subject:interior_space"
          ]
        }
      ],
      "secondary": [
        {
          "questionId": "mood",
          "rationale": "场景类型 audit always；氛围驱动型",
          "corpusFreq": 201,
          "source": "audit:always(demoted:与其他类型一致,mood不入essential)"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调；audit precision>=medium",
          "corpusFreq": 103,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "art_style",
          "rationale": "画风",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "composition",
          "rationale": "构图",
          "corpusFreq": 248,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "arch_viewpoint",
          "rationale": "P5 建筑视角（仰视/鸟瞰/室内等）；仅在建筑主体时激活",
          "corpusFreq": null,
          "source": "redesign:P5:arch-viewpoint",
          "scopeToOption": [
            "image_subject:architectural_exterior",
            "image_subject:interior_space"
          ]
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果；precision=high",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [
        {
          "questionId": "scene",
          "condition": {
            "dimension": "subject",
            "op": "in",
            "values": [
              "image_subject:natural_landscape",
              "image_subject:cityscape",
              "image_subject:skyscape"
            ]
          },
          "minPrecision": "any",
          "tierWhenActive": "suppress",
          "source": "redesign:P3:subject-scene-dedup"
        }
      ],
      "order": [
        "subject",
        "arch_style",
        "arch_type",
        "arch_material",
        "scene",
        "time_season",
        "weather",
        "camera",
        "camera_angle",
        "arch_viewpoint",
        "lighting",
        "mood",
        "color_palette",
        "art_style",
        "composition",
        "post_processing"
      ]
    },
    {
      "type": "动物",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "动物类型（宠物/野生动物）",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "framing",
          "rationale": "景别决定细节深度",
          "corpusFreq": null,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "场景/背景",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        // P4: breed + coat are the core differentiators — scoped to pet/wildlife
        {
          "questionId": "animal_breed",
          "rationale": "P4:品种是主体特化核心(宠物/野生动物)",
          "corpusFreq": null,
          "source": "redesign:P4",
          "scopeToOption": ["image_subject:pet_animal", "image_subject:wildlife"]
        },
        {
          "questionId": "animal_coat",
          "rationale": "P4:毛色/花纹，配合品种定义主体外观",
          "corpusFreq": null,
          "source": "redesign:P4",
          "scopeToOption": ["image_subject:pet_animal", "image_subject:wildlife"]
        }
        // constraints removed from essential — lives in shared.essential (dedup).
        // Ordering is controlled via the order array below.
      ],
      "secondary": [
        // P4: pose + expression scoped to pet/wildlife; expression activates at close-up
        {
          "questionId": "animal_pose",
          "rationale": "P4:姿态/动作，宠物/野生动物专属",
          "corpusFreq": null,
          "source": "redesign:P4",
          "scopeToOption": ["image_subject:pet_animal", "image_subject:wildlife"]
        },
        {
          "questionId": "animal_expression",
          "rationale": "P4:表情/神态，仅宠物(近景有效)",
          "corpusFreq": null,
          "source": "redesign:P4",
          "scopeToOption": ["image_subject:pet_animal"]
        },
        {
          "questionId": "lighting",
          "rationale": "光线（宠物/动物分支降级/pro 档，doc §3.3）",
          "corpusFreq": 580,
          "source": "redesign:P2:lighting-demote"
        },
        {
          "questionId": "art_style",
          "rationale": "画风；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "camera",
          "rationale": "镜头；audit 动物 precision>=medium（非 always）",
          "corpusFreq": 403,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调",
          "corpusFreq": 103,
          "source": "audit:precision>=medium"
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "animal_breed",
        "animal_coat",
        "framing",
        "animal_pose",
        "animal_expression",
        "scene",
        "lighting",
        "constraints",
        "art_style",
        "mood",
        "camera",
        "color_palette",
        "post_processing"
      ]
    },
    {
      "type": "食物/饮品",
      "essential": [
        {
          "questionId": "subject",
          "rationale": "食物类型",
          "corpusFreq": 667,
          "source": "audit:always"
        },
        {
          "questionId": "camera",
          "rationale": "拍摄角度对食物展示至关重要；audit always",
          "corpusFreq": 403,
          "source": "audit:always"
        },
        {
          "questionId": "scene",
          "rationale": "背景/环境",
          "corpusFreq": 860,
          "source": "audit:always"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "audit:always"
        },
      ],
      "secondary": [
        {
          "questionId": "color_palette",
          "rationale": "色调降级为 secondary（owner decision 3，去除 maintainer-override pin）",
          "corpusFreq": 103,
          "source": "redesign:P2:color-demote"
        },
        {
          "questionId": "art_style",
          "rationale": "画风；audit precision>=medium",
          "corpusFreq": 435,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "mood",
          "rationale": "情绪/氛围",
          "corpusFreq": 201,
          "source": "audit:precision>=medium"
        },
        {
          "questionId": "food_state",
          "rationale": "P7 food state — visual surface properties and freshness/heat signals",
          "source": "redesign:P7",
          "scopeToOption": [
            "image_subject:food_beverage",
            "image_subject:plated_dish",
            "image_subject:dessert_beverage",
          ],
        },
        {
          "questionId": "food_tableware_styling",
          "rationale": "P7 food tableware — plates, boards, glassware, surface props",
          "source": "redesign:P7",
          "scopeToOption": [
            "image_subject:food_beverage",
            "image_subject:plated_dish",
            "image_subject:dessert_beverage",
          ],
        }
      ],
      "tertiary": [
        {
          "questionId": "post_processing",
          "rationale": "后期效果",
          "corpusFreq": null,
          "source": "audit:precision=high"
        }
      ],
      "conditional": [],
      "order": [
        "subject",
        "camera",
        "scene",
        "lighting",
        "color_palette",
        "art_style",
        "mood",
        "food_state",
        "food_tableware_styling",
        "post_processing"
      ]
    },
    {
      "type": "通用",
      "essential": [
        {
          "questionId": "aspect_ratio",
          "source": "audit:always"
        },
        {
          "questionId": "constraints",
          "source": "audit:always"
        },
        {
          "questionId": "subject",
          "rationale": "主体",
          "corpusFreq": 667,
          "source": "fallback-CORE"
        },
        {
          "questionId": "scene",
          "rationale": "场景",
          "corpusFreq": 860,
          "source": "fallback-CORE"
        },
        {
          "questionId": "lighting",
          "rationale": "光线",
          "corpusFreq": 580,
          "source": "fallback-CORE"
        },
        {
          "questionId": "art_style",
          "rationale": "风格",
          "corpusFreq": 435,
          "source": "fallback-CORE"
        },
        {
          "questionId": "color_palette",
          "rationale": "色调",
          "corpusFreq": 103,
          "source": "fallback-CORE"
        }
      ],
      "secondary": [],
      "tertiary": [],
      "conditional": [],
      "order": [
        "subject",
        "scene",
        "lighting",
        "art_style",
        "color_palette"
      ]
    }
  ]
};
